<#
  worldmonitor-local installer (Windows)

  Run this from inside the extracted bundle folder, in PowerShell:

      .\install.ps1

  If PowerShell blocks the script:
      powershell -ExecutionPolicy Bypass -File .\install.ps1

  It installs production npm deps, writes a minimal .env from your answers, and
  registers a per-user Scheduled Task (WorldMonitorLocal) that starts the
  backend at logon. No administrator rights required. This folder becomes the
  permanent install location — do NOT move it afterwards; if you must, move it
  first and re-run this.
#>

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

function Say  ($m) { Write-Host "`n$m" -ForegroundColor Cyan }
function Info ($m) { Write-Host "  $m" }
function Die  ($m) { Write-Host "`nerror: $m" -ForegroundColor Red; exit 1 }

# --- preflight -----------------------------------------------------------
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Die "Node.js not found. Install Node >= 22.5.0 (https://nodejs.org) and re-run."
}
$nodeVer = (& node -p "process.versions.node")
$maj = [int]($nodeVer.Split('.')[0]); $min = [int]($nodeVer.Split('.')[1])
if ($maj -lt 22 -or ($maj -eq 22 -and $min -lt 5)) {
  Die "Node $nodeVer is too old — the backend uses the built-in node:sqlite (stable since 22.5.0). Upgrade and re-run."
}

Say "worldmonitor-local installer (Windows)"
Info "install location: $ScriptDir"
Info "node:            v$nodeVer"

# --- 1. production dependencies ---------------------------------------
# --ignore-scripts: the only postinstall is patch-package, a devDependency
# that patches @nitric/sdk, which the standalone backend never loads.
Say "Installing production dependencies (npm ci --omit=dev --ignore-scripts)..."
& npm ci --omit=dev --ignore-scripts
if ($LASTEXITCODE -ne 0) { Die "npm ci failed." }

# --- 2. .env --------------------------------------------------------
if (Test-Path .env) {
  Say ".env already exists — keeping it. Delete it and re-run to reconfigure."
} else {
  Say "Configuring .env"
  Info "Two values are required (the Supabase project this fork uses)."
  Info "The rest are optional — press Enter to skip."
  Write-Host ""

  function PromptRequired ($label) {
    do { $v = Read-Host "  $label" } while ([string]::IsNullOrWhiteSpace($v))
    return $v
  }
  function PromptOptional ($label) {
    $v = Read-Host "  $label (optional)"
    return $v
  }

  $supaUrl = PromptRequired 'Supabase URL  (https://xxxx.supabase.co)'
  $supaKey = PromptRequired 'Supabase publishable/anon key'
  Write-Host ""
  Info "Upstash Redis keeps the dashboard fresh. Without it the backend still"
  Info "serves whatever is already cached and freshness badges read 'unknown'."
  $upUrl = PromptOptional 'Upstash Redis REST URL'
  $upRo = ''; $upRw = ''
  if (-not [string]::IsNullOrWhiteSpace($upUrl)) {
    Info "  read-only token  -> local cache sync (required for a live dashboard)"
    $upRo = PromptOptional '  Upstash read-only token'
    Info "  full token       -> /api/health freshness badges (read-only is not enough)"
    $upRw = PromptOptional '  Upstash full token'
  }
  Write-Host ""
  $openrouter = PromptOptional 'OpenRouter API key  - enables AI summary panels'

  $lines = @(
    "# Generated by install.ps1 on $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    "# See .env.example for every supported key."
    "LOCAL_API_MODE=tauri-sidecar"
    "VITE_SUPABASE_URL=$supaUrl"
    "SUPABASE_URL=$supaUrl"
    "VITE_SUPABASE_PUBLISHABLE_KEY=$supaKey"
  )
  if (-not [string]::IsNullOrWhiteSpace($upUrl)) { $lines += "UPSTASH_REDIS_REST_URL=$upUrl" }
  if (-not [string]::IsNullOrWhiteSpace($upRo))  { $lines += "UPSTASH_REDIS_REST_READONLY_TOKEN=$upRo" }
  if (-not [string]::IsNullOrWhiteSpace($upRw))  { $lines += "UPSTASH_REDIS_REST_TOKEN=$upRw" }
  if (-not [string]::IsNullOrWhiteSpace($openrouter)) { $lines += "OPENROUTER_API_KEY=$openrouter" }
  Set-Content -Path .env -Value $lines -Encoding utf8
  Info "wrote $ScriptDir\.env"
}

# --- 3. Scheduled Task ----------------------------------------------
Say "Registering the Scheduled Task..."
& node scripts/worldmonitor-local.mjs install
if ($LASTEXITCODE -ne 0) { Die "worldmonitor-local install failed." }

Say "Status"
& node scripts/worldmonitor-local.mjs status

# --- 4. VS Code extension -----------------------------------------
$vsix = Get-ChildItem -Path $ScriptDir -Filter *.vsix | Select-Object -First 1
if ($vsix) {
  if (Get-Command code -ErrorAction SilentlyContinue) {
    Say "Installing the VS Code extension"
    & code --install-extension $vsix.FullName --force
  } else {
    Say "VS Code extension"
    Info "'code' CLI not on PATH. Install it manually:"
    Info "  VS Code -> Extensions -> ... -> Install from VSIX... -> $($vsix.FullName)"
  }
}

# --- done ---------------------------------------------------------
Say "Done."
@"
  Next steps:

  1. Sign in (for your personalised Latest Brief):
       node scripts/worldmonitor-local.mjs login
     One-time operator setup: the Supabase project must allowlist
       http://127.0.0.1:46124/callback
     under Auth -> URL Configuration -> Redirect URLs.

  2. In VS Code, run the command:
       WorldMonitor: Open Local Dashboard

  Manage the backend:
     node scripts/worldmonitor-local.mjs status
     node scripts/worldmonitor-local.mjs restart
     node scripts/worldmonitor-local.mjs uninstall
"@ | Write-Host
