#!/usr/bin/env bash
#
# worldmonitor-local installer (macOS)
#
# Run this from inside the extracted bundle folder:
#
#     ./install.sh
#
# It installs production npm deps, writes a minimal .env from your answers,
# and registers the launchd background service (com.worldmonitor.local-api).
# This folder becomes the permanent install location — do NOT move it after
# running the installer. If you must move it, move it first, then re-run this.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
die()  { printf '\n\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ── preflight ────────────────────────────────────────────────────────────
[ "$(uname -s)" = "Darwin" ] || die "this installer is macOS-only (launchd). Detected: $(uname -s)"

command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node >= 22.5.0 (https://nodejs.org) and re-run."
command -v npm  >/dev/null 2>&1 || die "npm not found alongside node."

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
NODE_MINOR="$(node -p 'process.versions.node.split(".")[1]')"
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 5 ]; }; then
  die "Node $(node -v) is too old — the backend uses the built-in node:sqlite (stable since 22.5.0). Upgrade and re-run."
fi

say "worldmonitor-local installer"
info "install location: $SCRIPT_DIR"
info "node:            $(node -v)"

# ── 1. production dependencies ─────────────────────────────────────────
# --ignore-scripts: the only postinstall is patch-package, a devDependency
# that patches @nitric/sdk. The standalone backend never loads @nitric/sdk,
# so skipping it is correct here (and --omit=dev would break the hook anyway).
say "Installing production dependencies (npm ci --omit=dev --ignore-scripts)…"
npm ci --omit=dev --ignore-scripts

# ── 2. .env ───────────────────────────────────────────────────────────
if [ -f .env ]; then
  say ".env already exists — keeping it. Delete it and re-run to reconfigure."
else
  say "Configuring .env"
  info "Two values are required (the Supabase project this fork uses)."
  info "The rest are optional — press Enter to skip."
  echo

  prompt_required() {  # $1 var name, $2 label
    local val=""
    while [ -z "$val" ]; do
      read -r -p "  $2: " val
      [ -z "$val" ] && echo "    (required)"
    done
    printf '%s' "$val"
  }
  prompt_optional() {  # $1 label
    local val=""
    read -r -p "  $1 (optional): " val
    printf '%s' "$val"
  }

  SUPA_URL="$(prompt_required VITE_SUPABASE_URL 'Supabase URL  (https://xxxx.supabase.co)')"
  SUPA_KEY="$(prompt_required VITE_SUPABASE_PUBLISHABLE_KEY 'Supabase publishable/anon key')"
  echo
  info "Upstash Redis keeps the dashboard fresh. Without it the backend still"
  info "serves whatever is already in the local cache, but nothing refreshes it"
  info "and the panel freshness badges read 'unknown'."
  UPSTASH_URL="$(prompt_optional 'Upstash Redis REST URL')"
  UPSTASH_RO=""
  UPSTASH_RW=""
  if [ -n "$UPSTASH_URL" ]; then
    info "  read-only token  → local cache sync (required for a live dashboard)"
    UPSTASH_RO="$(prompt_optional '  Upstash read-only token')"
    info "  full token       → /api/health freshness badges (read-only is not enough here)"
    UPSTASH_RW="$(prompt_optional '  Upstash full token')"
  fi
  echo
  OPENROUTER="$(prompt_optional 'OpenRouter API key  — enables AI summary panels')"

  {
    echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# See .env.example for every supported key."
    echo "LOCAL_API_MODE=tauri-sidecar"
    echo "VITE_SUPABASE_URL=$SUPA_URL"
    echo "SUPABASE_URL=$SUPA_URL"
    echo "VITE_SUPABASE_PUBLISHABLE_KEY=$SUPA_KEY"
    [ -n "$UPSTASH_URL" ] && echo "UPSTASH_REDIS_REST_URL=$UPSTASH_URL"
    [ -n "$UPSTASH_RO" ]  && echo "UPSTASH_REDIS_REST_READONLY_TOKEN=$UPSTASH_RO"
    [ -n "$UPSTASH_RW" ]  && echo "UPSTASH_REDIS_REST_TOKEN=$UPSTASH_RW"
    [ -n "$OPENROUTER" ]  && echo "OPENROUTER_API_KEY=$OPENROUTER"
  } > .env
  chmod 600 .env
  info "wrote $SCRIPT_DIR/.env (0600)"
fi

# ── 3. launchd service ────────────────────────────────────────────────
say "Registering the launchd service…"
node scripts/worldmonitor-local.mjs install

say "Status"
node scripts/worldmonitor-local.mjs status || true

# ── 4. VS Code extension ──────────────────────────────────────────────
VSIX="$(ls -1 "$SCRIPT_DIR"/*.vsix 2>/dev/null | head -n1 || true)"
if [ -n "$VSIX" ]; then
  if command -v code >/dev/null 2>&1; then
    say "Installing the VS Code extension"
    code --install-extension "$VSIX" --force && info "installed $(basename "$VSIX")"
  else
    say "VS Code extension"
    info "'code' CLI not on PATH. Install the extension manually:"
    info "  VS Code → Extensions → ⋯ → Install from VSIX… → $VSIX"
  fi
fi

# ── done ─────────────────────────────────────────────────────────────
say "Done."
cat <<EOF
  Next steps:

  1. Sign in (for your personalised Latest Brief):
       node scripts/worldmonitor-local.mjs login
     One-time operator setup: the Supabase project must allowlist
       http://127.0.0.1:46124/callback
     under Auth → URL Configuration → Redirect URLs.

  2. In VS Code, run the command:
       WorldMonitor: Open Local Dashboard

  Manage the backend:
     node scripts/worldmonitor-local.mjs status     # health at a glance
     node scripts/worldmonitor-local.mjs restart    # after an upgrade
     node scripts/worldmonitor-local.mjs uninstall  # remove the service
EOF
