#!/usr/bin/env bash
#
# worldmonitor-local installer (macOS)
#
# Run this from inside the extracted bundle folder:
#
#     ./install.sh                     # use ./org.env if present, else prompt
#     ./install.sh --config path/to/org.env
#
# The bundle is org-neutral: it carries no Supabase/Upstash values. Your org
# supplies them in an `org.env` file (KEY=value lines) — drop it next to this
# script as `org.env`, pass it with --config, or point $WM_ORG_ENV at it. With
# none of those, the installer prompts for the two required Supabase values.
#
# It installs production npm deps, writes .env, and registers the launchd
# background service (com.worldmonitor.local-api). This folder becomes the
# permanent install location — do NOT move it after running the installer. If
# you must move it, move it first, then re-run this.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── args ─────────────────────────────────────────────────────────────────
ORG_ENV="${WM_ORG_ENV:-}"
while [ $# -gt 0 ]; do
  case "$1" in
    --config) ORG_ENV="${2:-}"; shift 2 ;;
    --config=*) ORG_ENV="${1#--config=}"; shift ;;
    *) shift ;;
  esac
done
[ -z "$ORG_ENV" ] && [ -f "$SCRIPT_DIR/org.env" ] && ORG_ENV="$SCRIPT_DIR/org.env"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
die()  { printf '\n\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ── preflight ────────────────────────────────────────────────────────────
[ "$(uname -s)" = "Darwin" ] || die "this installer is macOS-only (launchd). Detected: $(uname -s)"

command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node >= 22.5.0 (https://nodejs.org) and re-run."
command -v npm  >/dev/null 2>&1 || die "npm not found alongside node."

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
NODE_MINOR="$(node -p 'process.versions.node.split(".")[1]')"
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 5 ]; }; then
  die "Node $(node -v) is too old — the backend uses the built-in node:sqlite (stable since 22.5.0). Upgrade and re-run."
fi

say "worldmonitor-local installer"
info "install location: $SCRIPT_DIR"
info "node:            $(node -v)"

# ── 1. production dependencies ─────────────────────────────────────────
# --ignore-scripts: the only postinstall is patch-package, a devDependency
# that patches @nitric/sdk. The standalone backend never loads @nitric/sdk,
# so skipping it is correct here (and --omit=dev would break the hook anyway).
say "Installing production dependencies (npm ci --omit=dev --ignore-scripts)…"
npm ci --omit=dev --ignore-scripts

# ── 2. .env ───────────────────────────────────────────────────────────
if [ -f .env ]; then
  say ".env already exists — keeping it. Delete it and re-run to reconfigure."
elif [ -n "$ORG_ENV" ]; then
  [ -f "$ORG_ENV" ] || die "config file not found: $ORG_ENV"
  say "Configuring .env from $ORG_ENV"
  grep -qE '^[[:space:]]*VITE_SUPABASE_URL=..*'            "$ORG_ENV" || die "$ORG_ENV is missing VITE_SUPABASE_URL"
  grep -qE '^[[:space:]]*VITE_SUPABASE_PUBLISHABLE_KEY=..*' "$ORG_ENV" || die "$ORG_ENV is missing VITE_SUPABASE_PUBLISHABLE_KEY"
  {
    echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) from $ORG_ENV"
    echo "# AI summary panels: add OPENROUTER_API_KEY=... here yourself if you want them."
    echo "LOCAL_API_MODE=tauri-sidecar"
    # everything from org.env except a LOCAL_API_MODE it might also carry
    grep -vE '^[[:space:]]*(#|LOCAL_API_MODE=|$)' "$ORG_ENV"
    # mirror VITE_SUPABASE_URL to SUPABASE_URL if org.env didn't set it
    grep -qE '^[[:space:]]*SUPABASE_URL=' "$ORG_ENV" || \
      grep -E '^[[:space:]]*VITE_SUPABASE_URL=' "$ORG_ENV" | sed 's/^[[:space:]]*VITE_//'
  } > .env
  chmod 600 .env
  info "wrote $SCRIPT_DIR/.env (0600)"
else
  say "Configuring .env"
  info "No org.env found (drop one next to this script, or pass --config)."
  info "Two values are required (your org's Supabase project)."
  info "The rest are optional — press Enter to skip."
  echo

  prompt_required() {  # $1 var name, $2 label
    local val=""
    while [ -z "$val" ]; do
      read -r -p "  $2: " val
      [ -z "$val" ] && echo "    (required)"
    done
    printf '%s' "$val"
  }
  prompt_optional() {  # $1 label
    local val=""
    read -r -p "  $1 (optional): " val
    printf '%s' "$val"
  }

  SUPA_URL="$(prompt_required VITE_SUPABASE_URL 'Supabase URL  (https://xxxx.supabase.co)')"
  SUPA_KEY="$(prompt_required VITE_SUPABASE_PUBLISHABLE_KEY 'Supabase publishable/anon key')"
  echo
  info "Upstash Redis keeps the local cache fresh. Without it the backend still"
  info "serves whatever is already cached, but nothing refreshes it."
  info "Only the READ-ONLY token is asked for — a local instance never needs, and"
  info "should never hold, a write credential to the shared store."
  UPSTASH_URL="$(prompt_optional 'Upstash Redis REST URL')"
  UPSTASH_RO=""
  if [ -n "$UPSTASH_URL" ]; then
    UPSTASH_RO="$(prompt_optional '  Upstash read-only token')"
  fi

  {
    echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# See .env.example for every supported key."
    echo "# AI summary panels: add OPENROUTER_API_KEY=... here yourself if you want them."
    echo "LOCAL_API_MODE=tauri-sidecar"
    echo "VITE_SUPABASE_URL=$SUPA_URL"
    echo "SUPABASE_URL=$SUPA_URL"
    echo "VITE_SUPABASE_PUBLISHABLE_KEY=$SUPA_KEY"
    [ -n "$UPSTASH_URL" ] && echo "UPSTASH_REDIS_REST_URL=$UPSTASH_URL"
    [ -n "$UPSTASH_RO" ]  && echo "UPSTASH_REDIS_REST_READONLY_TOKEN=$UPSTASH_RO"
  } > .env
  chmod 600 .env
  info "wrote $SCRIPT_DIR/.env (0600)"
fi

# ── 2b. seed ~/.worldmonitor/config.db ───────────────────────────────
# .env stays the primary source (node --env-file loads it); config.db is the
# same values in a store the in-app settings panel can edit later. Only the
# allow-listed keys are copied — never a shared write credential.
if [ -f .env ]; then
  node scripts/worldmonitor-local.mjs config import .env || \
    info "note: could not seed config.db (non-fatal; .env is still authoritative)"
fi

# ── 3. launchd service ────────────────────────────────────────────────
say "Registering the launchd service…"
node scripts/worldmonitor-local.mjs install

say "Status"
node scripts/worldmonitor-local.mjs status || true

# ── 4. VS Code extension ──────────────────────────────────────────────
VSIX="$(ls -1 "$SCRIPT_DIR"/*.vsix 2>/dev/null | head -n1 || true)"
if [ -n "$VSIX" ]; then
  if command -v code >/dev/null 2>&1; then
    say "Installing the VS Code extension"
    code --install-extension "$VSIX" --force && info "installed $(basename "$VSIX")"
  else
    say "VS Code extension"
    info "'code' CLI not on PATH. Install the extension manually:"
    info "  VS Code → Extensions → ⋯ → Install from VSIX… → $VSIX"
  fi
fi

# ── done ─────────────────────────────────────────────────────────────
say "Done."
cat <<EOF
  Next steps:

  1. Sign in (for your personalised Latest Brief):
       node scripts/worldmonitor-local.mjs login
     One-time operator setup: the Supabase project must allowlist
       http://127.0.0.1:46124/callback
     under Auth → URL Configuration → Redirect URLs.

  2. In VS Code, run the command:
       WorldMonitor: Open Local Dashboard

  Manage the backend:
     node scripts/worldmonitor-local.mjs status     # health at a glance
     node scripts/worldmonitor-local.mjs restart    # after an upgrade
     node scripts/worldmonitor-local.mjs uninstall  # remove the service
EOF
