#!/usr/bin/env bash
#
# worldmonitor-local setup (macOS) — run from inside an already-extracted bundle.
#
#     ./setup.sh                     # use ./org.env if present, else prompt
#     ./setup.sh --config path/to/org.env
#
# Most people don't run this directly — the one-command installer
# (curl -fsSL <release>/install | sh) fetches Node + the bundle and then calls
# this. Run it by hand only for a manual / headless / offline install.
#
# The bundle is org-neutral: it carries no Supabase/Upstash values. Your org
# supplies them in an `org.env` file (KEY=value lines) — drop it next to this
# script as `org.env`, pass it with --config, or point $WM_ORG_ENV at it. With
# none of those, the installer prompts for the two required Supabase values.
#
# It installs production npm deps, writes .env, and registers the launchd
# background service (com.worldmonitor.local-api). This folder becomes the
# permanent install location — do NOT move it after running this. If you must
# move it, move it first, then re-run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Prefer the pinned Node the bootstrap fetched into ~/.worldmonitor/runtime/
# (D15) over whatever is on PATH, so the whole toolchain — npm ci here and the
# long-lived service — runs on one known version.
WM_RUNTIME_BIN="$HOME/.worldmonitor/runtime/bin"
if [ -x "$WM_RUNTIME_BIN/node" ]; then
  export PATH="$WM_RUNTIME_BIN:$PATH"
fi

# ── args ─────────────────────────────────────────────────────────────────
ORG_ENV="${WM_ORG_ENV:-}"
while [ $# -gt 0 ]; do
  case "$1" in
    --config) ORG_ENV="${2:-}"; shift 2 ;;
    --config=*) ORG_ENV="${1#--config=}"; shift ;;
    *) shift ;;
  esac
done
[ -z "$ORG_ENV" ] && [ -f "$SCRIPT_DIR/org.env" ] && ORG_ENV="$SCRIPT_DIR/org.env"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
die()  { printf '\n\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ── preflight ────────────────────────────────────────────────────────────
[ "$(uname -s)" = "Darwin" ] || die "this installer is macOS-only (launchd). Detected: $(uname -s)"

command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node >= 22.5.0 (https://nodejs.org) and re-run."
command -v npm  >/dev/null 2>&1 || die "npm not found alongside node."

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
NODE_MINOR="$(node -p 'process.versions.node.split(".")[1]')"
if [ "$NODE_MAJOR" -lt 22 ] || { [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -lt 5 ]; }; then
  die "Node $(node -v) is too old — the backend uses the built-in node:sqlite (stable since 22.5.0). Upgrade and re-run."
fi

say "worldmonitor-local setup"
info "install location: $SCRIPT_DIR"
info "node:            $(node -v)   $(command -v node)"

# ── 1. production dependencies ─────────────────────────────────────────
# The slim backend package.json (scripts/release/backend-package.json, staged
# here as package.json) has no postinstall, so --ignore-scripts is belt-and-
# braces; --omit=dev installs the 5 runtime deps only (~39 pkgs / ~19 MB).
say "Installing production dependencies (npm ci --omit=dev --ignore-scripts)…"
npm ci --omit=dev --ignore-scripts

# ── 2. .env ───────────────────────────────────────────────────────────
if [ -f .env ]; then
  say ".env already exists — keeping it. Delete it and re-run to reconfigure."
elif [ -n "$ORG_ENV" ]; then
  [ -f "$ORG_ENV" ] || die "config file not found: $ORG_ENV"
  say "Configuring .env from $ORG_ENV"
  grep -qE '^[[:space:]]*VITE_SUPABASE_URL=..*'            "$ORG_ENV" || die "$ORG_ENV is missing VITE_SUPABASE_URL"
  grep -qE '^[[:space:]]*VITE_SUPABASE_PUBLISHABLE_KEY=..*' "$ORG_ENV" || die "$ORG_ENV is missing VITE_SUPABASE_PUBLISHABLE_KEY"
  {
    echo "# Generated by worldmonitor-local setup on $(date -u +%Y-%m-%dT%H:%M:%SZ) from $ORG_ENV"
    echo "# AI summary panels: add OPENROUTER_API_KEY=... here yourself if you want them."
    echo "LOCAL_API_MODE=tauri-sidecar"
    # everything from org.env except a LOCAL_API_MODE it might also carry
    grep -vE '^[[:space:]]*(#|LOCAL_API_MODE=|$)' "$ORG_ENV"
    # mirror VITE_SUPABASE_URL to SUPABASE_URL if org.env didn't set it
    grep -qE '^[[:space:]]*SUPABASE_URL=' "$ORG_ENV" || \
      grep -E '^[[:space:]]*VITE_SUPABASE_URL=' "$ORG_ENV" | sed 's/^[[:space:]]*VITE_//'
  } > .env
  chmod 600 .env
  info "wrote $SCRIPT_DIR/.env (0600)"
else
  say "Configuring .env"
  # Deliberately checks/reads /dev/tty, NOT stdin. Under the documented
  # one-liner (`curl -fsSL <release>/install | sh`), stdin IS the curl pipe
  # feeding the script itself — `[ ! -t 0 ]` is true and any `read` on stdin
  # hits an immediate EOF regardless of whether the user's real terminal is
  # interactive, making this prompt permanently unreachable via the
  # documented install path, not just in edge cases (found 2026-09-20 via a
  # genuinely clean wmtest re-test of v2.13.2). /dev/tty is the controlling
  # terminal regardless of stdin redirection — the standard fix for exactly
  # this curl-pipe-to-shell pattern. fd 3 opened read-write (not read-only):
  # some platforms' /dev/tty rejects a plain read-only open from a script
  # whose stdin isn't itself the tty.
  if ! exec 3<>/dev/tty 2>/dev/null; then
    die "no org.env found and no interactive terminal to prompt on. Pass --config <org.env>, set WM_ORG_ENV, or drop org.env (see org.env.example — needs VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY) next to this script."
  fi
  info "No org.env found (drop one next to this script, or pass --config)."
  info "Two values are required (your org's Supabase project)."
  info "The rest are optional — press Enter to skip."
  echo

  # Neither prompt_* function uses `read -p` for its label — deliberately.
  # `-p`'s own decision on whether to show its prompt depends on bash's
  # internal terminal-detection heuristic, and this exact function has
  # already produced two surprises from that class of thing (the `[ ! -t 0 ]`
  # stdin guard, then the stdout-capture leak). wmtest's Tier B pass on the
  # `<&3` version found a third: the fd-3/read mechanism and the required-value
  # retry loop both genuinely worked, but the `-p` label text itself never
  # rendered — indistinguishable from a real hang to a first-time user who
  # doesn't already know it secretly works. Printing the label directly to
  # fd 3 (the one fd we KNOW is the real tty, opened above) before a bare
  # `read` sidesteps `-p`'s visibility logic entirely rather than chasing why
  # it wasn't firing.
  prompt_required() {  # $1 var name, $2 label
    local val=""
    while [ -z "$val" ]; do
      printf '  %s: ' "$2" >&3
      read -r val <&3
      # >&2, not stdout: every call site captures this function's output via
      # command substitution ($(prompt_required ...)) to get $val. A plain
      # `echo` on stdout here doesn't just fail to reach the terminal on a
      # retry — it gets captured INTO the substitution ahead of the final
      # printf, corrupting the result into a literal multi-line
      # "    (required)\n<the real value>" string that then gets written to
      # .env verbatim. Confirmed via an isolated repro before fixing.
      [ -z "$val" ] && echo "    (required)" >&2
    done
    printf '%s' "$val"
  }
  prompt_optional() {  # $1 label
    local val=""
    printf '  %s (optional): ' "$1" >&3
    read -r val <&3
    printf '%s' "$val"
  }

  SUPA_URL="$(prompt_required VITE_SUPABASE_URL 'Supabase URL  (https://xxxx.supabase.co)')"
  SUPA_KEY="$(prompt_required VITE_SUPABASE_PUBLISHABLE_KEY 'Supabase publishable/anon key')"
  echo
  info "Upstash Redis keeps the local cache fresh. Without it the backend still"
  info "serves whatever is already cached, but nothing refreshes it."
  info "Only the READ-ONLY token is asked for — a local instance never needs, and"
  info "should never hold, a write credential to the shared store."
  UPSTASH_URL="$(prompt_optional 'Upstash Redis REST URL')"
  UPSTASH_RO=""
  if [ -n "$UPSTASH_URL" ]; then
    UPSTASH_RO="$(prompt_optional '  Upstash read-only token')"
  fi

  {
    echo "# Generated by worldmonitor-local setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# See .env.example for every supported key."
    echo "# AI summary panels: add OPENROUTER_API_KEY=... here yourself if you want them."
    echo "LOCAL_API_MODE=tauri-sidecar"
    echo "VITE_SUPABASE_URL=$SUPA_URL"
    echo "SUPABASE_URL=$SUPA_URL"
    echo "VITE_SUPABASE_PUBLISHABLE_KEY=$SUPA_KEY"
    [ -n "$UPSTASH_URL" ] && echo "UPSTASH_REDIS_REST_URL=$UPSTASH_URL"
    [ -n "$UPSTASH_RO" ]  && echo "UPSTASH_REDIS_REST_READONLY_TOKEN=$UPSTASH_RO"
  } > .env
  chmod 600 .env
  info "wrote $SCRIPT_DIR/.env (0600)"
  exec 3<&-
fi

# ── 2b. seed ~/.worldmonitor/config.db ───────────────────────────────
# .env stays the primary source (node --env-file loads it); config.db is the
# same values in a store the in-app settings panel can edit later. Only the
# allow-listed keys are copied — never a shared write credential.
if [ -f .env ]; then
  node scripts/worldmonitor-local.mjs config import .env || \
    info "note: could not seed config.db (non-fatal; .env is still authoritative)"
fi

# ── 3. launchd service ────────────────────────────────────────────────
# WM_SKIP_SERVICE=1 — install deps + .env only, don't register/start the
# service (CI smoke, containers, "I'll wire my own supervisor").
if [ "${WM_SKIP_SERVICE:-}" = "1" ]; then
  say "Skipping service registration (WM_SKIP_SERVICE=1)"
  node scripts/worldmonitor-local.mjs install --dry-run || true
else
  say "Registering the launchd service…"
  node scripts/worldmonitor-local.mjs install

  say "Status"
  node scripts/worldmonitor-local.mjs status || true
fi

# ── 4. VS Code extension ──────────────────────────────────────────────
VSIX="$(ls -1 "$SCRIPT_DIR"/*.vsix 2>/dev/null | head -n1 || true)"
if [ -n "$VSIX" ]; then
  if command -v code >/dev/null 2>&1; then
    say "Installing the VS Code extension"
    code --install-extension "$VSIX" --force && info "installed $(basename "$VSIX")"
  else
    say "VS Code extension"
    info "'code' CLI not on PATH. Install the extension manually:"
    info "  VS Code → Extensions → ⋯ → Install from VSIX… → $VSIX"
  fi
fi

# ── done ─────────────────────────────────────────────────────────────
DASHBOARD_URL="http://127.0.0.1:46123/"
say "Done."
cat <<EOF
  Open the local dashboard in a browser:
       $DASHBOARD_URL
  (bookmark it — there's no Desktop launcher; the CLI below covers the rest)

  Sign in (for your personalised Latest Brief) and manage the backend — cd
  here first, your shell isn't already sitting in this directory just
  because the installer's subshell was:
       cd $SCRIPT_DIR
       node scripts/worldmonitor-local.mjs login
     One-time operator setup — allowlist BOTH of these under the Supabase
     project's Auth → URL Configuration → Redirect URLs:
       http://127.0.0.1:46124/callback                      (this CLI login)
       http://localhost:46123/dashboard.html?embed=vscode   (sign-in inside VS Code)

  Then in VS Code run:  WorldMonitor: Open Local Dashboard

  Manage the backend (from $SCRIPT_DIR):
     node scripts/worldmonitor-local.mjs status     # health at a glance
     node scripts/worldmonitor-local.mjs restart    # after an upgrade
     node scripts/worldmonitor-local.mjs uninstall  # remove the service
EOF
