<#
  worldmonitor-local setup (Windows) — run from inside an already-extracted bundle.

      .\setup.ps1                       # uses .\org.env if present, else prompts
      .\setup.ps1 -Config path\to\org.env

  If PowerShell blocks the script:
      powershell -ExecutionPolicy Bypass -File .\setup.ps1

  Most people don't run this directly — the one-command installer
  (irm <release>/install.ps1 | iex) fetches Node + the bundle and then calls
  this. Run it by hand only for a manual / headless / offline install.

  The bundle is org-neutral: it carries no Supabase/Upstash values. Your org
  supplies them in an org.env file (KEY=value lines) — drop it next to this
  script as org.env, pass -Config, or set $env:WM_ORG_ENV. With none of those,
  the installer prompts for the two required Supabase values.

  It installs production npm deps, writes .env, and registers a per-user
  Scheduled Task (WorldMonitorLocal) that starts the backend at logon. No
  administrator rights required. This folder becomes the permanent install
  location — do NOT move it afterwards; if you must, move it first and re-run.
#>

param([string]$Config)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

# Prefer the pinned Node the bootstrap fetched into ~\.worldmonitor\runtime\
# (D15) over whatever is on PATH.
$WmRuntimeDir = Join-Path $env:USERPROFILE '.worldmonitor\runtime'
if (Test-Path (Join-Path $WmRuntimeDir 'node.exe')) {
  $env:PATH = "$WmRuntimeDir;$env:PATH"
}

$OrgEnv = $Config
if (-not $OrgEnv) { $OrgEnv = $env:WM_ORG_ENV }
if (-not $OrgEnv -and (Test-Path (Join-Path $ScriptDir 'org.env'))) { $OrgEnv = Join-Path $ScriptDir 'org.env' }

function Say  ($m) { Write-Host "`n$m" -ForegroundColor Cyan }
function Info ($m) { Write-Host "  $m" }
function Die  ($m) { Write-Host "`nerror: $m" -ForegroundColor Red; exit 1 }

# --- preflight -----------------------------------------------------------
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Die "Node.js not found. Install Node >= 22.5.0 (https://nodejs.org) and re-run."
}
$nodeVer = (& node -p "process.versions.node")
$maj = [int]($nodeVer.Split('.')[0]); $min = [int]($nodeVer.Split('.')[1])
if ($maj -lt 22 -or ($maj -eq 22 -and $min -lt 5)) {
  Die "Node $nodeVer is too old — the backend uses the built-in node:sqlite (stable since 22.5.0). Upgrade and re-run."
}

Say "worldmonitor-local setup (Windows)"
Info "install location: $ScriptDir"
Info "node:            v$nodeVer   $((Get-Command node).Source)"

# --- 1. production dependencies ---------------------------------------
# --ignore-scripts: the only postinstall is patch-package, a devDependency
# that patches @nitric/sdk, which the standalone backend never loads.
Say "Installing production dependencies (npm ci --omit=dev --ignore-scripts)..."
& npm ci --omit=dev --ignore-scripts
if ($LASTEXITCODE -ne 0) { Die "npm ci failed." }

# --- 2. .env --------------------------------------------------------
if (Test-Path .env) {
  Say ".env already exists — keeping it. Delete it and re-run to reconfigure."
} elseif ($OrgEnv) {
  if (-not (Test-Path $OrgEnv)) { Die "config file not found: $OrgEnv" }
  Say "Configuring .env from $OrgEnv"
  $orgLines = Get-Content $OrgEnv | Where-Object { $_ -notmatch '^\s*(#|LOCAL_API_MODE=|$)' }
  if (-not ($orgLines -match '^\s*VITE_SUPABASE_URL=..*'))            { Die "$OrgEnv is missing VITE_SUPABASE_URL" }
  if (-not ($orgLines -match '^\s*VITE_SUPABASE_PUBLISHABLE_KEY=..*')) { Die "$OrgEnv is missing VITE_SUPABASE_PUBLISHABLE_KEY" }
  $out = @(
    "# Generated by worldmonitor-local setup on $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')) from $OrgEnv"
    "# AI summary panels: add OPENROUTER_API_KEY=... here yourself if you want them."
    "LOCAL_API_MODE=tauri-sidecar"
  ) + $orgLines
  if (-not ($orgLines -match '^\s*SUPABASE_URL=')) {
    $out += ($orgLines | Where-Object { $_ -match '^\s*VITE_SUPABASE_URL=' } | ForEach-Object { $_ -replace '^\s*VITE_', '' })
  }
  Set-Content -Path .env -Value $out -Encoding utf8
  Info "wrote $ScriptDir\.env"
} else {
  Say "Configuring .env"
  Info "No org.env found (drop one next to this script, or pass -Config)."
  Info "Two values are required (your org's Supabase project)."
  Info "The rest are optional — press Enter to skip."
  Write-Host ""

  function PromptRequired ($label) {
    do { $v = Read-Host "  $label" } while ([string]::IsNullOrWhiteSpace($v))
    return $v
  }
  function PromptOptional ($label) {
    $v = Read-Host "  $label (optional)"
    return $v
  }

  $supaUrl = PromptRequired 'Supabase URL  (https://xxxx.supabase.co)'
  $supaKey = PromptRequired 'Supabase publishable/anon key'
  Write-Host ""
  Info "Upstash Redis keeps the local cache fresh. Without it the backend still"
  Info "serves whatever is already cached, but nothing refreshes it."
  Info "Only the READ-ONLY token is asked for - a local instance never needs, and"
  Info "should never hold, a write credential to the shared store."
  $upUrl = PromptOptional 'Upstash Redis REST URL'
  $upRo = ''
  if (-not [string]::IsNullOrWhiteSpace($upUrl)) {
    $upRo = PromptOptional '  Upstash read-only token'
  }

  $lines = @(
    "# Generated by worldmonitor-local setup on $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    "# See .env.example for every supported key."
    "# AI summary panels: add OPENROUTER_API_KEY=... here yourself if you want them."
    "LOCAL_API_MODE=tauri-sidecar"
    "VITE_SUPABASE_URL=$supaUrl"
    "SUPABASE_URL=$supaUrl"
    "VITE_SUPABASE_PUBLISHABLE_KEY=$supaKey"
  )
  if (-not [string]::IsNullOrWhiteSpace($upUrl)) { $lines += "UPSTASH_REDIS_REST_URL=$upUrl" }
  if (-not [string]::IsNullOrWhiteSpace($upRo))  { $lines += "UPSTASH_REDIS_REST_READONLY_TOKEN=$upRo" }
  Set-Content -Path .env -Value $lines -Encoding utf8
  Info "wrote $ScriptDir\.env"
}

# --- 2b. seed ~/.worldmonitor/config.db ---------------------------
# .env stays the primary source; config.db is the same values in a store the
# in-app settings panel can edit later. Only allow-listed keys are copied.
if (Test-Path .env) {
  & node scripts/worldmonitor-local.mjs config import .env
  if ($LASTEXITCODE -ne 0) { Info "note: could not seed config.db (non-fatal; .env is still authoritative)" }
}

# --- 3. Scheduled Task ----------------------------------------------
if ($env:WM_SKIP_SERVICE -eq '1') {
  Say "Skipping service registration (WM_SKIP_SERVICE=1)"
  & node scripts/worldmonitor-local.mjs install --dry-run
} else {
  Say "Registering the Scheduled Task..."
  & node scripts/worldmonitor-local.mjs install
  if ($LASTEXITCODE -ne 0) { Die "worldmonitor-local install failed." }

  Say "Status"
  & node scripts/worldmonitor-local.mjs status
}

# --- 4. VS Code extension -----------------------------------------
$vsix = Get-ChildItem -Path $ScriptDir -Filter *.vsix | Select-Object -First 1
if ($vsix) {
  if (Get-Command code -ErrorAction SilentlyContinue) {
    Say "Installing the VS Code extension"
    & code --install-extension $vsix.FullName --force
  } else {
    Say "VS Code extension"
    Info "'code' CLI not on PATH. Install it manually:"
    Info "  VS Code -> Extensions -> ... -> Install from VSIX... -> $($vsix.FullName)"
  }
}

# --- 5. Desktop launcher ----------------------------------------
# A .url internet shortcut on the Desktop that opens the control panel, with
# the bundled .ico for its Finder/Explorer icon.
$panelUrl = 'http://127.0.0.1:46123/settings.html'
$desktop = [Environment]::GetFolderPath('Desktop')
if ($desktop) {
  Say "Adding the Desktop launcher"
  $ico = Join-Path $ScriptDir 'assets\icon.ico'
  $lnk = Join-Path $desktop 'WorldMonitor.url'
  $lines = @('[InternetShortcut]', "URL=$panelUrl")
  if (Test-Path $ico) { $lines += "IconFile=$ico"; $lines += 'IconIndex=0' }
  Set-Content -Path $lnk -Value $lines -Encoding ascii
  Info "created $lnk"
}

# --- done ---------------------------------------------------------
Say "Done."
@"
  Open the backend control panel (config / sign in / status / restart):
       $panelUrl
  ...or double-click WorldMonitor on your Desktop.

  Headless / no browser? Sign in from the terminal instead:
       node scripts/worldmonitor-local.mjs login
     One-time operator setup: allowlist  http://127.0.0.1:46124/callback
     under the Supabase project's Auth -> URL Configuration -> Redirect URLs.

  Then in VS Code run:  WorldMonitor: Open Local Dashboard

  Manage the backend:
     node scripts/worldmonitor-local.mjs status
     node scripts/worldmonitor-local.mjs restart
     node scripts/worldmonitor-local.mjs uninstall
"@ | Write-Host
