// AUTO-GENERATED by scripts/sync-domain-config.mjs. DO NOT EDIT.
// Source: shared/domain-config.js

/**
 * Single source of truth for deriving domain-dependent values (CORS origin
 * allowlists, cookie scoping, canonical/www/api origins) from ONE configured
 * base domain instead of hardcoding a brand name across the codebase.
 *
 * This fork ships with NO built-in production domain. When no domain is
 * configured, every helper here defaults to local dev (`localhost:3000`,
 * matching vite.config.ts's DEV_PORT default) — never assume any brand is
 * "the" deployment. Each real deployment (including a future multi-instance
 * setup) supplies its own domain via configuration.
 *
 * Deliberately zero imports and no Node/browser globals (no `process.env`,
 * no `import.meta.env`) — every caller reads its own raw domain string from
 * whatever env mechanism *its* runtime has (Node's `process.env` in
 * api/server, the Cloudflare Worker's `env` binding param, `import.meta.env`
 * in the browser bundle) and passes it in as a plain string. That's what lets
 * this one module be: imported directly by server/ (TS build graph),
 * copy-synced into the unbundled plain-JS api/_cors.js (see
 * scripts/sync-domain-config.mjs), and bundled into the Cloudflare Worker via
 * wrangler's esbuild.
 */

const DEFAULT_APP_DOMAIN = 'localhost:3000';

/** Strips a leading scheme and trailing slash; '' | undefined -> the local default. */
function normalizeDomain(rawDomain) {
  const trimmed = (rawDomain ?? '').trim();
  if (!trimmed) return DEFAULT_APP_DOMAIN;
  return trimmed.replace(/^https?:\/\//i, '').replace(/\/+$/, '');
}

/** True for `localhost`/`127.0.0.1`, with or without a port. */
function isLocalDomain(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  return /^(localhost|127\.0\.0\.1)(:\d+)?$/i.test(domain);
}

/** 'http' for local dev, 'https' for anything else. */
function resolveProtocol(rawDomain) {
  return isLocalDomain(rawDomain) ? 'http' : 'https';
}

/** The apex origin, e.g. `http://localhost:3000` or `https://example.com`. */
function resolveAppOrigin(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  return `${resolveProtocol(domain)}://${domain}`;
}

/**
 * The `www.` origin — collapses to the apex origin on localhost, since a
 * `www.localhost:3000` subdomain doesn't mean anything for local dev.
 */
function resolveWwwOrigin(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return resolveAppOrigin(domain);
  return `${resolveProtocol(domain)}://www.${domain}`;
}

/**
 * The `api.` origin — collapses to the apex origin on localhost (local
 * installs serve the API from the same origin; see VITE_WS_API_URL's
 * documented same-domain-when-empty convention in .env.example).
 */
function resolveApiOrigin(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return resolveAppOrigin(domain);
  return `${resolveProtocol(domain)}://api.${domain}`;
}

/**
 * The `Set-Cookie: domain=` value for sharing a cookie across every
 * subdomain of the configured domain — null on localhost, since a
 * cross-subdomain cookie domain is meaningless there (and per RFC 6265,
 * browsers won't scope a cookie to `.localhost` sensibly anyway).
 */
function resolveCookieDomain(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return null;
  return `.${domain}`;
}

/** Escapes regex metacharacters so a configured domain is safe to embed in a pattern. */
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * A `RegExp` matching the configured domain and every subdomain of it
 * (mirrors the historical `/^https:\/\/(.*\.)?worldmonitor\.app$/` shape),
 * or null for a local domain — DEV_LOCALHOST_ORIGIN_PATTERNS covers that
 * case instead, since an https apex/subdomain pattern makes no sense for
 * `localhost:3000`.
 */
function buildDomainOriginPattern(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return null;
  const escaped = escapeRegExp(domain);
  return new RegExp(`^https:\\/\\/(.*\\.)?${escaped}$`);
}

/** Brand-agnostic origin patterns for the Tauri desktop runtime — unchanged from today's hardcoded list. */
const TAURI_ORIGIN_PATTERNS = Object.freeze([
  /^https?:\/\/tauri\.localhost(:\d+)?$/,
  /^https?:\/\/[a-z0-9-]+\.tauri\.localhost(:\d+)?$/i,
  /^tauri:\/\/localhost$/,
  /^asset:\/\/localhost$/,
]);

/** Bare localhost/127.0.0.1 origin patterns — brand-agnostic, dev-only. */
const DEV_LOCALHOST_ORIGIN_PATTERNS = Object.freeze([
  /^https?:\/\/localhost(:\d+)?$/,
  /^https?:\/\/127\.0\.0\.1(:\d+)?$/,
]);

/**
 * Builds the full CORS origin-allowlist pattern array for the configured
 * domain: the domain pattern (skipped on localhost) + Tauri origins + any
 * caller-supplied extra patterns (e.g. a Vercel-preview-deployment pattern,
 * which is infra-specific, not domain-specific, and stays local to each
 * caller rather than living in this module) + dev-only localhost patterns
 * when requested.
 */
function buildAllowedOriginPatterns(rawDomain, { includeDevPatterns = false, extraPatterns = [] } = {}) {
  const domainPattern = buildDomainOriginPattern(rawDomain);
  return [
    ...(domainPattern ? [domainPattern] : []),
    ...TAURI_ORIGIN_PATTERNS,
    ...extraPatterns,
    ...(includeDevPatterns ? DEV_LOCALHOST_ORIGIN_PATTERNS : []),
  ];
}

/**
 * The 5 "variant" (sector-focused) subdomains this fork can serve
 * (tech./finance./commodity./happy./energy.<domain>) — the single source
 * every variant-host list (dashboard routing, CSP, OG metadata, analytics
 * allowlists) should derive from instead of hand-duplicating the slug list.
 */
const VARIANT_SLUGS = Object.freeze(['tech', 'finance', 'commodity', 'happy', 'energy']);

/**
 * A variant's bare hostname, e.g. `tech.example.com` — collapses to the
 * apex domain on localhost, same reasoning as resolveWwwOrigin/resolveApiOrigin
 * (a `tech.localhost:3000` subdomain doesn't mean anything for local dev).
 */
function resolveVariantDomain(rawDomain, slug) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return domain;
  return `${slug}.${domain}`;
}

/** A variant's full origin, e.g. `https://tech.example.com`. */
function resolveVariantOrigin(rawDomain, slug) {
  const domain = normalizeDomain(rawDomain);
  return `${resolveProtocol(domain)}://${resolveVariantDomain(domain, slug)}`;
}

/** `{ tech: 'https://tech.example.com', finance: ..., ... }` for all 5 slugs, in VARIANT_SLUGS order. */
function resolveVariantOrigins(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  return Object.fromEntries(VARIANT_SLUGS.map((slug) => [slug, resolveVariantOrigin(domain, slug)]));
}

/**
 * The `proxy.` origin — the Railway-hosted widget-agent SSE relay subdomain
 * (api/widget-agent.ts, vite.config.ts's dev-server proxy). Same local-dev
 * collapse-to-apex behavior as the other named-subdomain resolvers.
 */
function resolveProxyOrigin(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return resolveAppOrigin(domain);
  return `${resolveProtocol(domain)}://proxy.${domain}`;
}

/**
 * Generic named-subdomain origin resolver (e.g. `status.`, `maps.`) — the
 * primitive resolveProxyOrigin/resolveApiOrigin/
 * resolveWwwOrigin are all thin wrappers over. Same local-dev
 * collapse-to-apex convention.
 */
function resolveSubdomainOrigin(rawDomain, subdomain) {
  const domain = normalizeDomain(rawDomain);
  if (isLocalDomain(domain)) return resolveAppOrigin(domain);
  return `${resolveProtocol(domain)}://${subdomain}.${domain}`;
}

/**
 * Domain-derived CSP origin lists for the `frame-src`/`frame-ancestors`/
 * `form-action` directives. Deliberately three small named functions
 * instead of one flag-driven builder: the three directives use different
 * orderings of the same underlying origins (frame-src puts the apex right
 * after www/before variants; frame-ancestors puts it last, after variants),
 * so hiding that in flag combinations would be less legible than just
 * writing each order out. Callers splice these into their own static
 * third-party allowlist (youtube, cloudflare, vercel.live, ...), which
 * stays local to each config file since it's infra-specific, not
 * domain-specific — same division of responsibility as buildAllowedOriginPatterns's extraPatterns.
 */
function buildCspFrameSrcOrigins(rawDomain) {
  const domain = normalizeDomain(rawDomain);
  const variants = resolveVariantOrigins(domain);
  return [resolveWwwOrigin(domain), resolveAppOrigin(domain), ...VARIANT_SLUGS.map((slug) => variants[slug])];
}

function buildCspFrameAncestorsOrigins(rawDomain, { includeVariants = true } = {}) {
  const domain = normalizeDomain(rawDomain);
  const variants = resolveVariantOrigins(domain);
  return [
    resolveWwwOrigin(domain),
    ...(includeVariants ? VARIANT_SLUGS.map((slug) => variants[slug]) : []),
    resolveAppOrigin(domain),
  ];
}

function buildCspFormActionOrigins(rawDomain) {
  return [resolveApiOrigin(rawDomain)];
}

module.exports = { DEFAULT_APP_DOMAIN, normalizeDomain, isLocalDomain, resolveProtocol, resolveAppOrigin, resolveWwwOrigin, resolveApiOrigin, resolveCookieDomain, buildDomainOriginPattern, TAURI_ORIGIN_PATTERNS, DEV_LOCALHOST_ORIGIN_PATTERNS, buildAllowedOriginPatterns, VARIANT_SLUGS, resolveVariantDomain, resolveVariantOrigin, resolveVariantOrigins, resolveProxyOrigin, resolveSubdomainOrigin, buildCspFrameSrcOrigins, buildCspFrameAncestorsOrigins, buildCspFormActionOrigins };
