/**
 * GENERATED FILE — do not hand-edit. Regenerate with:
 *   node scripts/generate-nitric-routes.mjs
 *
 * Mechanically registers every Vercel Edge handler under api/ (except
 * api/mcp.ts, handled separately) onto the Nitric `api` gateway declared
 * in gcp/api/main.ts. GET/POST/PUT/PATCH/DELETE/OPTIONS are all registered
 * for every route — each handler already enforces its own method
 * allowlist internally (same as it does today under Vercel, where one
 * edge function receives every verb), so this is not widening what a
 * route accepts.
 *
 * SKIPPED (visible gap, not silently dropped — see docs/architecture/
 * nitric-gcp-scaffold.md for what each of these needs):
 *   - api/[...notfound].ts (catch-all [...] segment — confirmed 2026-08-06 that Nitric itself has no wildcard route syntax, not just unsupported by this generator; see docs/architecture/nitric-gcp-scaffold.md)
 *   - api/data/city-coords.ts (no edge runtime config)
 *   - api/mcp/auth.ts (no edge runtime config)
 *   - api/mcp/billing-denial.ts (no edge runtime config)
 *   - api/mcp/constants.ts (no edge runtime config)
 *   - api/mcp/dispatch.ts (no edge runtime config)
 *   - api/mcp/downstream.ts (no edge runtime config)
 *   - api/mcp/error-fingerprint.ts (no edge runtime config)
 *   - api/mcp/filters.ts (no edge runtime config)
 *   - api/mcp/freshness.ts (no edge runtime config)
 *   - api/mcp/handler.ts (no edge runtime config)
 *   - api/mcp/jmespath.ts (no edge runtime config)
 *   - api/mcp/prompts/index.ts (no edge runtime config)
 *   - api/mcp/quota.ts (no edge runtime config)
 *   - api/mcp/registry/cache-tools.ts (no edge runtime config)
 *   - api/mcp/registry/index.ts (no edge runtime config)
 *   - api/mcp/registry/rpc-tools.ts (no edge runtime config)
 *   - api/mcp/resources/index.ts (no edge runtime config)
 *   - api/mcp/resources/slugs.ts (no edge runtime config)
 *   - api/mcp/rpc.ts (no edge runtime config)
 *   - api/mcp/telemetry.ts (no edge runtime config)
 *   - api/mcp/types.ts (no edge runtime config)
 *   - api/mcp/ui/chokepoint-monitor-app.ts (no edge runtime config)
 *   - api/mcp/ui/conflict-events-app.ts (no edge runtime config)
 *   - api/mcp/ui/country-brief-app.ts (no edge runtime config)
 *   - api/mcp/ui/country-risk-app.ts (no edge runtime config)
 *   - api/mcp/ui/forecasts-app.ts (no edge runtime config)
 *   - api/mcp/ui/market-radar-app.ts (no edge runtime config)
 *   - api/mcp/ui/natural-disasters-app.ts (no edge runtime config)
 *   - api/mcp/ui/news-intelligence-app.ts (no edge runtime config)
 *   - api/mcp/ui/prediction-markets-app.ts (no edge runtime config)
 *   - api/mcp/ui/registry.ts (no edge runtime config)
 *   - api/mcp/ui/shell.ts (no edge runtime config)
 *   - api/mcp/ui/world-brief-app.ts (no edge runtime config)
 *   - api/mcp/usage.ts (no edge runtime config)
 *   - api/mcp/utils.ts (no edge runtime config)
 *   - api/og-story.js (no edge runtime config)
 *   - api/story.js (no edge runtime config)
 */

import type { Api } from '@nitric/sdk';
import { adaptVercelHandler } from './adapt-vercel-handler';
import route_0_a2aHandler from '../../api/a2a';
import route_1_agent_authHandler from '../../api/agent-auth';
import route_2_askHandler from '../../api/ask';
import route_3_aviation_v1_rpcHandler from '../../api/aviation/v1/[rpc]';
import route_4_batch_v1_rpcHandler from '../../api/batch/v1/[rpc]';
// @ts-expect-error — JS module, no declaration file
import route_5_bootstrapHandler from '../../api/bootstrap.js';
import route_6_brief_userId_issueDateHandler from '../../api/brief/[userId]/[issueDate]';
import route_7_brief_carousel_userId_issueDate_pageHandler from '../../api/brief/carousel/[userId]/[issueDate]/[page]';
import route_8_brief_public_hashHandler from '../../api/brief/public/[hash]';
import route_9_brief_share_urlHandler from '../../api/brief/share-url';
// @ts-expect-error — JS module, no declaration file
import route_10_cache_purgeHandler from '../../api/cache-purge.js';
import route_11_chat_analystHandler from '../../api/chat-analyst';
import route_12_climate_v1_rpcHandler from '../../api/climate/v1/[rpc]';
import route_13_conflict_v1_rpcHandler from '../../api/conflict/v1/[rpc]';
import route_14_consumer_prices_v1_rpcHandler from '../../api/consumer-prices/v1/[rpc]';
import route_15_create_checkoutHandler from '../../api/create-checkout';
import route_16_customer_portalHandler from '../../api/customer-portal';
import route_17_cyber_v1_rpcHandler from '../../api/cyber/v1/[rpc]';
import route_18_discord_oauth_callbackHandler from '../../api/discord/oauth/callback';
import route_19_discord_oauth_startHandler from '../../api/discord/oauth/start';
import route_20_displacement_v1_rpcHandler from '../../api/displacement/v1/[rpc]';
import route_21_docs_mcpHandler from '../../api/docs-mcp';
// @ts-expect-error — JS module, no declaration file
import route_22_downloadHandler from '../../api/download.js';
import route_23_economic_v1_rpcHandler from '../../api/economic/v1/[rpc]';
import route_24_followed_countriesHandler from '../../api/followed-countries';
import route_25_forecast_v1_rpcHandler from '../../api/forecast/v1/[rpc]';
// @ts-expect-error — JS module, no declaration file
import route_26_fwdstartHandler from '../../api/fwdstart.js';
// @ts-expect-error — JS module, no declaration file
import route_27_geoHandler from '../../api/geo.js';
import route_28_giving_v1_rpcHandler from '../../api/giving/v1/[rpc]';
// @ts-expect-error — JS module, no declaration file
import route_29_gpsjamHandler from '../../api/gpsjam.js';
// @ts-expect-error — JS module, no declaration file
import route_30_healthHandler from '../../api/health.js';
import route_31_health_v1_rpcHandler from '../../api/health/v1/[rpc]';
import route_32_http_message_signatures_directoryHandler from '../../api/http-message-signatures-directory';
import route_33_imagery_v1_rpcHandler from '../../api/imagery/v1/[rpc]';
import route_34_infrastructure_v1_rpcHandler from '../../api/infrastructure/v1/[rpc]';
import route_35_intelligence_v1_rpcHandler from '../../api/intelligence/v1/[rpc]';
import route_36_internal_brief_why_mattersHandler from '../../api/internal/brief-why-matters';
import route_37_internal_mcp_grant_contextHandler from '../../api/internal/mcp-grant-context';
import route_38_internal_mcp_grant_mintHandler from '../../api/internal/mcp-grant-mint';
import route_39_invalidate_user_api_key_cacheHandler from '../../api/invalidate-user-api-key-cache';
import route_40_latest_briefHandler from '../../api/latest-brief';
import route_41_leads_v1_rpcHandler from '../../api/leads/v1/[rpc]';
import route_42_maritime_v1_rpcHandler from '../../api/maritime/v1/[rpc]';
import route_43_market_v1_rpcHandler from '../../api/market/v1/[rpc]';
import route_44_mcp_proxyHandler from '../../api/mcp-proxy';
import route_45_me_entitlementHandler from '../../api/me/entitlement';
import route_46_military_v1_rpcHandler from '../../api/military/v1/[rpc]';
import route_47_natural_v1_rpcHandler from '../../api/natural/v1/[rpc]';
import route_48_news_v1_rpcHandler from '../../api/news/v1/[rpc]';
import route_49_not_foundHandler from '../../api/not-found';
import route_50_notification_channelsHandler from '../../api/notification-channels';
import route_51_notifyHandler from '../../api/notify';
import route_52_oauth_authorization_serverHandler from '../../api/oauth-authorization-server';
import route_53_oauth_protected_resourceHandler from '../../api/oauth-protected-resource';
import route_54_oauth_authorize_proHandler from '../../api/oauth/authorize-pro';
// @ts-expect-error — JS module, no declaration file
import route_55_oauth_authorizeHandler from '../../api/oauth/authorize.js';
// @ts-expect-error — JS module, no declaration file
import route_56_oauth_registerHandler from '../../api/oauth/register.js';
import route_57_oauth_tokenHandler from '../../api/oauth/token';
// @ts-expect-error — JS module, no declaration file
import route_58_openskyHandler from '../../api/opensky.js';
// @ts-expect-error — JS module, no declaration file
import route_59_oref_alertsHandler from '../../api/oref-alerts.js';
// @ts-expect-error — JS module, no declaration file
import route_60_polymarketHandler from '../../api/polymarket.js';
import route_61_positive_events_v1_rpcHandler from '../../api/positive-events/v1/[rpc]';
import route_62_prediction_v1_rpcHandler from '../../api/prediction/v1/[rpc]';
// @ts-expect-error — JS module, no declaration file
import route_63_product_catalogHandler from '../../api/product-catalog.js';
import route_64_radiation_v1_rpcHandler from '../../api/radiation/v1/[rpc]';
import route_65_referral_meHandler from '../../api/referral/me';
import route_66_research_v1_rpcHandler from '../../api/research/v1/[rpc]';
import route_67_resilience_v1_rpcHandler from '../../api/resilience/v1/[rpc]';
// @ts-expect-error — JS module, no declaration file
import route_68_reverse_geocodeHandler from '../../api/reverse-geocode.js';
// @ts-expect-error — JS module, no declaration file
import route_69_rss_proxyHandler from '../../api/rss-proxy.js';
import route_70_sanctions_v1_rpcHandler from '../../api/sanctions/v1/[rpc]';
import route_71_scenario_v1_rpcHandler from '../../api/scenario/v1/[rpc]';
import route_72_scenario_v1_runHandler from '../../api/scenario/v1/run';
import route_73_scenario_v1_statusHandler from '../../api/scenario/v1/status';
import route_74_scenario_v1_templatesHandler from '../../api/scenario/v1/templates';
// @ts-expect-error — JS module, no declaration file
import route_75_security_reportHandler from '../../api/security/report.js';
import route_76_seed_contract_probeHandler from '../../api/seed-contract-probe';
// @ts-expect-error — JS module, no declaration file
import route_77_seed_healthHandler from '../../api/seed-health.js';
import route_78_seismology_v1_rpcHandler from '../../api/seismology/v1/[rpc]';
import route_79_skills_fetch_agentskillsHandler from '../../api/skills/fetch-agentskills';
import route_80_slack_oauth_callbackHandler from '../../api/slack/oauth/callback';
import route_81_slack_oauth_startHandler from '../../api/slack/oauth/start';
// @ts-expect-error — JS module, no declaration file
import route_82_supply_chain_hormuz_trackerHandler from '../../api/supply-chain/hormuz-tracker.js';
import route_83_supply_chain_v1_rpcHandler from '../../api/supply-chain/v1/[rpc]';
import route_84_supply_chain_v1_country_productsHandler from '../../api/supply-chain/v1/country-products';
import route_85_supply_chain_v1_multi_sector_cost_shockHandler from '../../api/supply-chain/v1/multi-sector-cost-shock';
import route_86_symbol_searchHandler from '../../api/symbol-search';
// @ts-expect-error — JS module, no declaration file
import route_87_telegram_feedHandler from '../../api/telegram-feed.js';
import route_88_telegram_pair_callbackHandler from '../../api/telegram/pair-callback';
import route_89_thermal_v1_rpcHandler from '../../api/thermal/v1/[rpc]';
import route_90_trade_v1_rpcHandler from '../../api/trade/v1/[rpc]';
import route_91_unrest_v1_rpcHandler from '../../api/unrest/v1/[rpc]';
import route_92_user_prefsHandler from '../../api/user-prefs';
import route_93_user_mcp_quotaHandler from '../../api/user/mcp-quota';
import route_94_user_mcp_revokeHandler from '../../api/user/mcp-revoke';
import route_95_v2_shipping_rpcHandler from '../../api/v2/shipping/[rpc]';
import route_96_v2_shipping_webhooks_subscriberIdHandler from '../../api/v2/shipping/webhooks/[subscriberId]';
import route_97_v2_shipping_webhooks_subscriberId_actionHandler from '../../api/v2/shipping/webhooks/[subscriberId]/[action]';
// @ts-expect-error — JS module, no declaration file
import route_98_versionHandler from '../../api/version.js';
import route_99_webcam_v1_rpcHandler from '../../api/webcam/v1/[rpc]';
import route_100_widget_agentHandler from '../../api/widget-agent';
import route_101_wildfire_v1_rpcHandler from '../../api/wildfire/v1/[rpc]';
// @ts-expect-error — JS module, no declaration file
import route_102_wm_sessionHandler from '../../api/wm-session.js';
// @ts-expect-error — JS module, no declaration file
import route_103_youtube_embedHandler from '../../api/youtube/embed.js';
// @ts-expect-error — JS module, no declaration file
import route_104_youtube_liveHandler from '../../api/youtube/live.js';

export function registerGeneratedRoutes(api: Api): void {
  const route_0_a2a = api.route('/api/a2a');
  route_0_a2a.get(adaptVercelHandler(route_0_a2aHandler));
  route_0_a2a.post(adaptVercelHandler(route_0_a2aHandler));
  route_0_a2a.put(adaptVercelHandler(route_0_a2aHandler));
  route_0_a2a.patch(adaptVercelHandler(route_0_a2aHandler));
  route_0_a2a.delete(adaptVercelHandler(route_0_a2aHandler));
  route_0_a2a.options(adaptVercelHandler(route_0_a2aHandler));
  const route_1_agent_auth = api.route('/api/agent-auth');
  route_1_agent_auth.get(adaptVercelHandler(route_1_agent_authHandler));
  route_1_agent_auth.post(adaptVercelHandler(route_1_agent_authHandler));
  route_1_agent_auth.put(adaptVercelHandler(route_1_agent_authHandler));
  route_1_agent_auth.patch(adaptVercelHandler(route_1_agent_authHandler));
  route_1_agent_auth.delete(adaptVercelHandler(route_1_agent_authHandler));
  route_1_agent_auth.options(adaptVercelHandler(route_1_agent_authHandler));
  const route_2_ask = api.route('/api/ask');
  route_2_ask.get(adaptVercelHandler(route_2_askHandler));
  route_2_ask.post(adaptVercelHandler(route_2_askHandler));
  route_2_ask.put(adaptVercelHandler(route_2_askHandler));
  route_2_ask.patch(adaptVercelHandler(route_2_askHandler));
  route_2_ask.delete(adaptVercelHandler(route_2_askHandler));
  route_2_ask.options(adaptVercelHandler(route_2_askHandler));
  const route_3_aviation_v1_rpc = api.route('/api/aviation/v1/:rpc');
  route_3_aviation_v1_rpc.get(adaptVercelHandler(route_3_aviation_v1_rpcHandler));
  route_3_aviation_v1_rpc.post(adaptVercelHandler(route_3_aviation_v1_rpcHandler));
  route_3_aviation_v1_rpc.put(adaptVercelHandler(route_3_aviation_v1_rpcHandler));
  route_3_aviation_v1_rpc.patch(adaptVercelHandler(route_3_aviation_v1_rpcHandler));
  route_3_aviation_v1_rpc.delete(adaptVercelHandler(route_3_aviation_v1_rpcHandler));
  route_3_aviation_v1_rpc.options(adaptVercelHandler(route_3_aviation_v1_rpcHandler));
  const route_4_batch_v1_rpc = api.route('/api/batch/v1/:rpc');
  route_4_batch_v1_rpc.get(adaptVercelHandler(route_4_batch_v1_rpcHandler));
  route_4_batch_v1_rpc.post(adaptVercelHandler(route_4_batch_v1_rpcHandler));
  route_4_batch_v1_rpc.put(adaptVercelHandler(route_4_batch_v1_rpcHandler));
  route_4_batch_v1_rpc.patch(adaptVercelHandler(route_4_batch_v1_rpcHandler));
  route_4_batch_v1_rpc.delete(adaptVercelHandler(route_4_batch_v1_rpcHandler));
  route_4_batch_v1_rpc.options(adaptVercelHandler(route_4_batch_v1_rpcHandler));
  const route_5_bootstrap = api.route('/api/bootstrap');
  route_5_bootstrap.get(adaptVercelHandler(route_5_bootstrapHandler));
  route_5_bootstrap.post(adaptVercelHandler(route_5_bootstrapHandler));
  route_5_bootstrap.put(adaptVercelHandler(route_5_bootstrapHandler));
  route_5_bootstrap.patch(adaptVercelHandler(route_5_bootstrapHandler));
  route_5_bootstrap.delete(adaptVercelHandler(route_5_bootstrapHandler));
  route_5_bootstrap.options(adaptVercelHandler(route_5_bootstrapHandler));
  const route_6_brief_userId_issueDate = api.route('/api/brief/:userId/:issueDate');
  route_6_brief_userId_issueDate.get(adaptVercelHandler(route_6_brief_userId_issueDateHandler));
  route_6_brief_userId_issueDate.post(adaptVercelHandler(route_6_brief_userId_issueDateHandler));
  route_6_brief_userId_issueDate.put(adaptVercelHandler(route_6_brief_userId_issueDateHandler));
  route_6_brief_userId_issueDate.patch(adaptVercelHandler(route_6_brief_userId_issueDateHandler));
  route_6_brief_userId_issueDate.delete(adaptVercelHandler(route_6_brief_userId_issueDateHandler));
  route_6_brief_userId_issueDate.options(adaptVercelHandler(route_6_brief_userId_issueDateHandler));
  const route_7_brief_carousel_userId_issueDate_page = api.route('/api/brief/carousel/:userId/:issueDate/:page');
  route_7_brief_carousel_userId_issueDate_page.get(adaptVercelHandler(route_7_brief_carousel_userId_issueDate_pageHandler));
  route_7_brief_carousel_userId_issueDate_page.post(adaptVercelHandler(route_7_brief_carousel_userId_issueDate_pageHandler));
  route_7_brief_carousel_userId_issueDate_page.put(adaptVercelHandler(route_7_brief_carousel_userId_issueDate_pageHandler));
  route_7_brief_carousel_userId_issueDate_page.patch(adaptVercelHandler(route_7_brief_carousel_userId_issueDate_pageHandler));
  route_7_brief_carousel_userId_issueDate_page.delete(adaptVercelHandler(route_7_brief_carousel_userId_issueDate_pageHandler));
  route_7_brief_carousel_userId_issueDate_page.options(adaptVercelHandler(route_7_brief_carousel_userId_issueDate_pageHandler));
  const route_8_brief_public_hash = api.route('/api/brief/public/:hash');
  route_8_brief_public_hash.get(adaptVercelHandler(route_8_brief_public_hashHandler));
  route_8_brief_public_hash.post(adaptVercelHandler(route_8_brief_public_hashHandler));
  route_8_brief_public_hash.put(adaptVercelHandler(route_8_brief_public_hashHandler));
  route_8_brief_public_hash.patch(adaptVercelHandler(route_8_brief_public_hashHandler));
  route_8_brief_public_hash.delete(adaptVercelHandler(route_8_brief_public_hashHandler));
  route_8_brief_public_hash.options(adaptVercelHandler(route_8_brief_public_hashHandler));
  const route_9_brief_share_url = api.route('/api/brief/share-url');
  route_9_brief_share_url.get(adaptVercelHandler(route_9_brief_share_urlHandler));
  route_9_brief_share_url.post(adaptVercelHandler(route_9_brief_share_urlHandler));
  route_9_brief_share_url.put(adaptVercelHandler(route_9_brief_share_urlHandler));
  route_9_brief_share_url.patch(adaptVercelHandler(route_9_brief_share_urlHandler));
  route_9_brief_share_url.delete(adaptVercelHandler(route_9_brief_share_urlHandler));
  route_9_brief_share_url.options(adaptVercelHandler(route_9_brief_share_urlHandler));
  const route_10_cache_purge = api.route('/api/cache-purge');
  route_10_cache_purge.get(adaptVercelHandler(route_10_cache_purgeHandler));
  route_10_cache_purge.post(adaptVercelHandler(route_10_cache_purgeHandler));
  route_10_cache_purge.put(adaptVercelHandler(route_10_cache_purgeHandler));
  route_10_cache_purge.patch(adaptVercelHandler(route_10_cache_purgeHandler));
  route_10_cache_purge.delete(adaptVercelHandler(route_10_cache_purgeHandler));
  route_10_cache_purge.options(adaptVercelHandler(route_10_cache_purgeHandler));
  const route_11_chat_analyst = api.route('/api/chat-analyst');
  route_11_chat_analyst.get(adaptVercelHandler(route_11_chat_analystHandler));
  route_11_chat_analyst.post(adaptVercelHandler(route_11_chat_analystHandler));
  route_11_chat_analyst.put(adaptVercelHandler(route_11_chat_analystHandler));
  route_11_chat_analyst.patch(adaptVercelHandler(route_11_chat_analystHandler));
  route_11_chat_analyst.delete(adaptVercelHandler(route_11_chat_analystHandler));
  route_11_chat_analyst.options(adaptVercelHandler(route_11_chat_analystHandler));
  const route_12_climate_v1_rpc = api.route('/api/climate/v1/:rpc');
  route_12_climate_v1_rpc.get(adaptVercelHandler(route_12_climate_v1_rpcHandler));
  route_12_climate_v1_rpc.post(adaptVercelHandler(route_12_climate_v1_rpcHandler));
  route_12_climate_v1_rpc.put(adaptVercelHandler(route_12_climate_v1_rpcHandler));
  route_12_climate_v1_rpc.patch(adaptVercelHandler(route_12_climate_v1_rpcHandler));
  route_12_climate_v1_rpc.delete(adaptVercelHandler(route_12_climate_v1_rpcHandler));
  route_12_climate_v1_rpc.options(adaptVercelHandler(route_12_climate_v1_rpcHandler));
  const route_13_conflict_v1_rpc = api.route('/api/conflict/v1/:rpc');
  route_13_conflict_v1_rpc.get(adaptVercelHandler(route_13_conflict_v1_rpcHandler));
  route_13_conflict_v1_rpc.post(adaptVercelHandler(route_13_conflict_v1_rpcHandler));
  route_13_conflict_v1_rpc.put(adaptVercelHandler(route_13_conflict_v1_rpcHandler));
  route_13_conflict_v1_rpc.patch(adaptVercelHandler(route_13_conflict_v1_rpcHandler));
  route_13_conflict_v1_rpc.delete(adaptVercelHandler(route_13_conflict_v1_rpcHandler));
  route_13_conflict_v1_rpc.options(adaptVercelHandler(route_13_conflict_v1_rpcHandler));
  const route_14_consumer_prices_v1_rpc = api.route('/api/consumer-prices/v1/:rpc');
  route_14_consumer_prices_v1_rpc.get(adaptVercelHandler(route_14_consumer_prices_v1_rpcHandler));
  route_14_consumer_prices_v1_rpc.post(adaptVercelHandler(route_14_consumer_prices_v1_rpcHandler));
  route_14_consumer_prices_v1_rpc.put(adaptVercelHandler(route_14_consumer_prices_v1_rpcHandler));
  route_14_consumer_prices_v1_rpc.patch(adaptVercelHandler(route_14_consumer_prices_v1_rpcHandler));
  route_14_consumer_prices_v1_rpc.delete(adaptVercelHandler(route_14_consumer_prices_v1_rpcHandler));
  route_14_consumer_prices_v1_rpc.options(adaptVercelHandler(route_14_consumer_prices_v1_rpcHandler));
  const route_15_create_checkout = api.route('/api/create-checkout');
  route_15_create_checkout.get(adaptVercelHandler(route_15_create_checkoutHandler));
  route_15_create_checkout.post(adaptVercelHandler(route_15_create_checkoutHandler));
  route_15_create_checkout.put(adaptVercelHandler(route_15_create_checkoutHandler));
  route_15_create_checkout.patch(adaptVercelHandler(route_15_create_checkoutHandler));
  route_15_create_checkout.delete(adaptVercelHandler(route_15_create_checkoutHandler));
  route_15_create_checkout.options(adaptVercelHandler(route_15_create_checkoutHandler));
  const route_16_customer_portal = api.route('/api/customer-portal');
  route_16_customer_portal.get(adaptVercelHandler(route_16_customer_portalHandler));
  route_16_customer_portal.post(adaptVercelHandler(route_16_customer_portalHandler));
  route_16_customer_portal.put(adaptVercelHandler(route_16_customer_portalHandler));
  route_16_customer_portal.patch(adaptVercelHandler(route_16_customer_portalHandler));
  route_16_customer_portal.delete(adaptVercelHandler(route_16_customer_portalHandler));
  route_16_customer_portal.options(adaptVercelHandler(route_16_customer_portalHandler));
  const route_17_cyber_v1_rpc = api.route('/api/cyber/v1/:rpc');
  route_17_cyber_v1_rpc.get(adaptVercelHandler(route_17_cyber_v1_rpcHandler));
  route_17_cyber_v1_rpc.post(adaptVercelHandler(route_17_cyber_v1_rpcHandler));
  route_17_cyber_v1_rpc.put(adaptVercelHandler(route_17_cyber_v1_rpcHandler));
  route_17_cyber_v1_rpc.patch(adaptVercelHandler(route_17_cyber_v1_rpcHandler));
  route_17_cyber_v1_rpc.delete(adaptVercelHandler(route_17_cyber_v1_rpcHandler));
  route_17_cyber_v1_rpc.options(adaptVercelHandler(route_17_cyber_v1_rpcHandler));
  const route_18_discord_oauth_callback = api.route('/api/discord/oauth/callback');
  route_18_discord_oauth_callback.get(adaptVercelHandler(route_18_discord_oauth_callbackHandler));
  route_18_discord_oauth_callback.post(adaptVercelHandler(route_18_discord_oauth_callbackHandler));
  route_18_discord_oauth_callback.put(adaptVercelHandler(route_18_discord_oauth_callbackHandler));
  route_18_discord_oauth_callback.patch(adaptVercelHandler(route_18_discord_oauth_callbackHandler));
  route_18_discord_oauth_callback.delete(adaptVercelHandler(route_18_discord_oauth_callbackHandler));
  route_18_discord_oauth_callback.options(adaptVercelHandler(route_18_discord_oauth_callbackHandler));
  const route_19_discord_oauth_start = api.route('/api/discord/oauth/start');
  route_19_discord_oauth_start.get(adaptVercelHandler(route_19_discord_oauth_startHandler));
  route_19_discord_oauth_start.post(adaptVercelHandler(route_19_discord_oauth_startHandler));
  route_19_discord_oauth_start.put(adaptVercelHandler(route_19_discord_oauth_startHandler));
  route_19_discord_oauth_start.patch(adaptVercelHandler(route_19_discord_oauth_startHandler));
  route_19_discord_oauth_start.delete(adaptVercelHandler(route_19_discord_oauth_startHandler));
  route_19_discord_oauth_start.options(adaptVercelHandler(route_19_discord_oauth_startHandler));
  const route_20_displacement_v1_rpc = api.route('/api/displacement/v1/:rpc');
  route_20_displacement_v1_rpc.get(adaptVercelHandler(route_20_displacement_v1_rpcHandler));
  route_20_displacement_v1_rpc.post(adaptVercelHandler(route_20_displacement_v1_rpcHandler));
  route_20_displacement_v1_rpc.put(adaptVercelHandler(route_20_displacement_v1_rpcHandler));
  route_20_displacement_v1_rpc.patch(adaptVercelHandler(route_20_displacement_v1_rpcHandler));
  route_20_displacement_v1_rpc.delete(adaptVercelHandler(route_20_displacement_v1_rpcHandler));
  route_20_displacement_v1_rpc.options(adaptVercelHandler(route_20_displacement_v1_rpcHandler));
  const route_21_docs_mcp = api.route('/api/docs-mcp');
  route_21_docs_mcp.get(adaptVercelHandler(route_21_docs_mcpHandler));
  route_21_docs_mcp.post(adaptVercelHandler(route_21_docs_mcpHandler));
  route_21_docs_mcp.put(adaptVercelHandler(route_21_docs_mcpHandler));
  route_21_docs_mcp.patch(adaptVercelHandler(route_21_docs_mcpHandler));
  route_21_docs_mcp.delete(adaptVercelHandler(route_21_docs_mcpHandler));
  route_21_docs_mcp.options(adaptVercelHandler(route_21_docs_mcpHandler));
  const route_22_download = api.route('/api/download');
  route_22_download.get(adaptVercelHandler(route_22_downloadHandler));
  route_22_download.post(adaptVercelHandler(route_22_downloadHandler));
  route_22_download.put(adaptVercelHandler(route_22_downloadHandler));
  route_22_download.patch(adaptVercelHandler(route_22_downloadHandler));
  route_22_download.delete(adaptVercelHandler(route_22_downloadHandler));
  route_22_download.options(adaptVercelHandler(route_22_downloadHandler));
  const route_23_economic_v1_rpc = api.route('/api/economic/v1/:rpc');
  route_23_economic_v1_rpc.get(adaptVercelHandler(route_23_economic_v1_rpcHandler));
  route_23_economic_v1_rpc.post(adaptVercelHandler(route_23_economic_v1_rpcHandler));
  route_23_economic_v1_rpc.put(adaptVercelHandler(route_23_economic_v1_rpcHandler));
  route_23_economic_v1_rpc.patch(adaptVercelHandler(route_23_economic_v1_rpcHandler));
  route_23_economic_v1_rpc.delete(adaptVercelHandler(route_23_economic_v1_rpcHandler));
  route_23_economic_v1_rpc.options(adaptVercelHandler(route_23_economic_v1_rpcHandler));
  const route_24_followed_countries = api.route('/api/followed-countries');
  route_24_followed_countries.get(adaptVercelHandler(route_24_followed_countriesHandler));
  route_24_followed_countries.post(adaptVercelHandler(route_24_followed_countriesHandler));
  route_24_followed_countries.put(adaptVercelHandler(route_24_followed_countriesHandler));
  route_24_followed_countries.patch(adaptVercelHandler(route_24_followed_countriesHandler));
  route_24_followed_countries.delete(adaptVercelHandler(route_24_followed_countriesHandler));
  route_24_followed_countries.options(adaptVercelHandler(route_24_followed_countriesHandler));
  const route_25_forecast_v1_rpc = api.route('/api/forecast/v1/:rpc');
  route_25_forecast_v1_rpc.get(adaptVercelHandler(route_25_forecast_v1_rpcHandler));
  route_25_forecast_v1_rpc.post(adaptVercelHandler(route_25_forecast_v1_rpcHandler));
  route_25_forecast_v1_rpc.put(adaptVercelHandler(route_25_forecast_v1_rpcHandler));
  route_25_forecast_v1_rpc.patch(adaptVercelHandler(route_25_forecast_v1_rpcHandler));
  route_25_forecast_v1_rpc.delete(adaptVercelHandler(route_25_forecast_v1_rpcHandler));
  route_25_forecast_v1_rpc.options(adaptVercelHandler(route_25_forecast_v1_rpcHandler));
  const route_26_fwdstart = api.route('/api/fwdstart');
  route_26_fwdstart.get(adaptVercelHandler(route_26_fwdstartHandler));
  route_26_fwdstart.post(adaptVercelHandler(route_26_fwdstartHandler));
  route_26_fwdstart.put(adaptVercelHandler(route_26_fwdstartHandler));
  route_26_fwdstart.patch(adaptVercelHandler(route_26_fwdstartHandler));
  route_26_fwdstart.delete(adaptVercelHandler(route_26_fwdstartHandler));
  route_26_fwdstart.options(adaptVercelHandler(route_26_fwdstartHandler));
  const route_27_geo = api.route('/api/geo');
  route_27_geo.get(adaptVercelHandler(route_27_geoHandler));
  route_27_geo.post(adaptVercelHandler(route_27_geoHandler));
  route_27_geo.put(adaptVercelHandler(route_27_geoHandler));
  route_27_geo.patch(adaptVercelHandler(route_27_geoHandler));
  route_27_geo.delete(adaptVercelHandler(route_27_geoHandler));
  route_27_geo.options(adaptVercelHandler(route_27_geoHandler));
  const route_28_giving_v1_rpc = api.route('/api/giving/v1/:rpc');
  route_28_giving_v1_rpc.get(adaptVercelHandler(route_28_giving_v1_rpcHandler));
  route_28_giving_v1_rpc.post(adaptVercelHandler(route_28_giving_v1_rpcHandler));
  route_28_giving_v1_rpc.put(adaptVercelHandler(route_28_giving_v1_rpcHandler));
  route_28_giving_v1_rpc.patch(adaptVercelHandler(route_28_giving_v1_rpcHandler));
  route_28_giving_v1_rpc.delete(adaptVercelHandler(route_28_giving_v1_rpcHandler));
  route_28_giving_v1_rpc.options(adaptVercelHandler(route_28_giving_v1_rpcHandler));
  const route_29_gpsjam = api.route('/api/gpsjam');
  route_29_gpsjam.get(adaptVercelHandler(route_29_gpsjamHandler));
  route_29_gpsjam.post(adaptVercelHandler(route_29_gpsjamHandler));
  route_29_gpsjam.put(adaptVercelHandler(route_29_gpsjamHandler));
  route_29_gpsjam.patch(adaptVercelHandler(route_29_gpsjamHandler));
  route_29_gpsjam.delete(adaptVercelHandler(route_29_gpsjamHandler));
  route_29_gpsjam.options(adaptVercelHandler(route_29_gpsjamHandler));
  const route_30_health = api.route('/api/health');
  route_30_health.get(adaptVercelHandler(route_30_healthHandler));
  route_30_health.post(adaptVercelHandler(route_30_healthHandler));
  route_30_health.put(adaptVercelHandler(route_30_healthHandler));
  route_30_health.patch(adaptVercelHandler(route_30_healthHandler));
  route_30_health.delete(adaptVercelHandler(route_30_healthHandler));
  route_30_health.options(adaptVercelHandler(route_30_healthHandler));
  const route_31_health_v1_rpc = api.route('/api/health/v1/:rpc');
  route_31_health_v1_rpc.get(adaptVercelHandler(route_31_health_v1_rpcHandler));
  route_31_health_v1_rpc.post(adaptVercelHandler(route_31_health_v1_rpcHandler));
  route_31_health_v1_rpc.put(adaptVercelHandler(route_31_health_v1_rpcHandler));
  route_31_health_v1_rpc.patch(adaptVercelHandler(route_31_health_v1_rpcHandler));
  route_31_health_v1_rpc.delete(adaptVercelHandler(route_31_health_v1_rpcHandler));
  route_31_health_v1_rpc.options(adaptVercelHandler(route_31_health_v1_rpcHandler));
  const route_32_http_message_signatures_directory = api.route('/api/http-message-signatures-directory');
  route_32_http_message_signatures_directory.get(adaptVercelHandler(route_32_http_message_signatures_directoryHandler));
  route_32_http_message_signatures_directory.post(adaptVercelHandler(route_32_http_message_signatures_directoryHandler));
  route_32_http_message_signatures_directory.put(adaptVercelHandler(route_32_http_message_signatures_directoryHandler));
  route_32_http_message_signatures_directory.patch(adaptVercelHandler(route_32_http_message_signatures_directoryHandler));
  route_32_http_message_signatures_directory.delete(adaptVercelHandler(route_32_http_message_signatures_directoryHandler));
  route_32_http_message_signatures_directory.options(adaptVercelHandler(route_32_http_message_signatures_directoryHandler));
  const route_33_imagery_v1_rpc = api.route('/api/imagery/v1/:rpc');
  route_33_imagery_v1_rpc.get(adaptVercelHandler(route_33_imagery_v1_rpcHandler));
  route_33_imagery_v1_rpc.post(adaptVercelHandler(route_33_imagery_v1_rpcHandler));
  route_33_imagery_v1_rpc.put(adaptVercelHandler(route_33_imagery_v1_rpcHandler));
  route_33_imagery_v1_rpc.patch(adaptVercelHandler(route_33_imagery_v1_rpcHandler));
  route_33_imagery_v1_rpc.delete(adaptVercelHandler(route_33_imagery_v1_rpcHandler));
  route_33_imagery_v1_rpc.options(adaptVercelHandler(route_33_imagery_v1_rpcHandler));
  const route_34_infrastructure_v1_rpc = api.route('/api/infrastructure/v1/:rpc');
  route_34_infrastructure_v1_rpc.get(adaptVercelHandler(route_34_infrastructure_v1_rpcHandler));
  route_34_infrastructure_v1_rpc.post(adaptVercelHandler(route_34_infrastructure_v1_rpcHandler));
  route_34_infrastructure_v1_rpc.put(adaptVercelHandler(route_34_infrastructure_v1_rpcHandler));
  route_34_infrastructure_v1_rpc.patch(adaptVercelHandler(route_34_infrastructure_v1_rpcHandler));
  route_34_infrastructure_v1_rpc.delete(adaptVercelHandler(route_34_infrastructure_v1_rpcHandler));
  route_34_infrastructure_v1_rpc.options(adaptVercelHandler(route_34_infrastructure_v1_rpcHandler));
  const route_35_intelligence_v1_rpc = api.route('/api/intelligence/v1/:rpc');
  route_35_intelligence_v1_rpc.get(adaptVercelHandler(route_35_intelligence_v1_rpcHandler));
  route_35_intelligence_v1_rpc.post(adaptVercelHandler(route_35_intelligence_v1_rpcHandler));
  route_35_intelligence_v1_rpc.put(adaptVercelHandler(route_35_intelligence_v1_rpcHandler));
  route_35_intelligence_v1_rpc.patch(adaptVercelHandler(route_35_intelligence_v1_rpcHandler));
  route_35_intelligence_v1_rpc.delete(adaptVercelHandler(route_35_intelligence_v1_rpcHandler));
  route_35_intelligence_v1_rpc.options(adaptVercelHandler(route_35_intelligence_v1_rpcHandler));
  const route_36_internal_brief_why_matters = api.route('/api/internal/brief-why-matters');
  route_36_internal_brief_why_matters.get(adaptVercelHandler(route_36_internal_brief_why_mattersHandler));
  route_36_internal_brief_why_matters.post(adaptVercelHandler(route_36_internal_brief_why_mattersHandler));
  route_36_internal_brief_why_matters.put(adaptVercelHandler(route_36_internal_brief_why_mattersHandler));
  route_36_internal_brief_why_matters.patch(adaptVercelHandler(route_36_internal_brief_why_mattersHandler));
  route_36_internal_brief_why_matters.delete(adaptVercelHandler(route_36_internal_brief_why_mattersHandler));
  route_36_internal_brief_why_matters.options(adaptVercelHandler(route_36_internal_brief_why_mattersHandler));
  const route_37_internal_mcp_grant_context = api.route('/api/internal/mcp-grant-context');
  route_37_internal_mcp_grant_context.get(adaptVercelHandler(route_37_internal_mcp_grant_contextHandler));
  route_37_internal_mcp_grant_context.post(adaptVercelHandler(route_37_internal_mcp_grant_contextHandler));
  route_37_internal_mcp_grant_context.put(adaptVercelHandler(route_37_internal_mcp_grant_contextHandler));
  route_37_internal_mcp_grant_context.patch(adaptVercelHandler(route_37_internal_mcp_grant_contextHandler));
  route_37_internal_mcp_grant_context.delete(adaptVercelHandler(route_37_internal_mcp_grant_contextHandler));
  route_37_internal_mcp_grant_context.options(adaptVercelHandler(route_37_internal_mcp_grant_contextHandler));
  const route_38_internal_mcp_grant_mint = api.route('/api/internal/mcp-grant-mint');
  route_38_internal_mcp_grant_mint.get(adaptVercelHandler(route_38_internal_mcp_grant_mintHandler));
  route_38_internal_mcp_grant_mint.post(adaptVercelHandler(route_38_internal_mcp_grant_mintHandler));
  route_38_internal_mcp_grant_mint.put(adaptVercelHandler(route_38_internal_mcp_grant_mintHandler));
  route_38_internal_mcp_grant_mint.patch(adaptVercelHandler(route_38_internal_mcp_grant_mintHandler));
  route_38_internal_mcp_grant_mint.delete(adaptVercelHandler(route_38_internal_mcp_grant_mintHandler));
  route_38_internal_mcp_grant_mint.options(adaptVercelHandler(route_38_internal_mcp_grant_mintHandler));
  const route_39_invalidate_user_api_key_cache = api.route('/api/invalidate-user-api-key-cache');
  route_39_invalidate_user_api_key_cache.get(adaptVercelHandler(route_39_invalidate_user_api_key_cacheHandler));
  route_39_invalidate_user_api_key_cache.post(adaptVercelHandler(route_39_invalidate_user_api_key_cacheHandler));
  route_39_invalidate_user_api_key_cache.put(adaptVercelHandler(route_39_invalidate_user_api_key_cacheHandler));
  route_39_invalidate_user_api_key_cache.patch(adaptVercelHandler(route_39_invalidate_user_api_key_cacheHandler));
  route_39_invalidate_user_api_key_cache.delete(adaptVercelHandler(route_39_invalidate_user_api_key_cacheHandler));
  route_39_invalidate_user_api_key_cache.options(adaptVercelHandler(route_39_invalidate_user_api_key_cacheHandler));
  const route_40_latest_brief = api.route('/api/latest-brief');
  route_40_latest_brief.get(adaptVercelHandler(route_40_latest_briefHandler));
  route_40_latest_brief.post(adaptVercelHandler(route_40_latest_briefHandler));
  route_40_latest_brief.put(adaptVercelHandler(route_40_latest_briefHandler));
  route_40_latest_brief.patch(adaptVercelHandler(route_40_latest_briefHandler));
  route_40_latest_brief.delete(adaptVercelHandler(route_40_latest_briefHandler));
  route_40_latest_brief.options(adaptVercelHandler(route_40_latest_briefHandler));
  const route_41_leads_v1_rpc = api.route('/api/leads/v1/:rpc');
  route_41_leads_v1_rpc.get(adaptVercelHandler(route_41_leads_v1_rpcHandler));
  route_41_leads_v1_rpc.post(adaptVercelHandler(route_41_leads_v1_rpcHandler));
  route_41_leads_v1_rpc.put(adaptVercelHandler(route_41_leads_v1_rpcHandler));
  route_41_leads_v1_rpc.patch(adaptVercelHandler(route_41_leads_v1_rpcHandler));
  route_41_leads_v1_rpc.delete(adaptVercelHandler(route_41_leads_v1_rpcHandler));
  route_41_leads_v1_rpc.options(adaptVercelHandler(route_41_leads_v1_rpcHandler));
  const route_42_maritime_v1_rpc = api.route('/api/maritime/v1/:rpc');
  route_42_maritime_v1_rpc.get(adaptVercelHandler(route_42_maritime_v1_rpcHandler));
  route_42_maritime_v1_rpc.post(adaptVercelHandler(route_42_maritime_v1_rpcHandler));
  route_42_maritime_v1_rpc.put(adaptVercelHandler(route_42_maritime_v1_rpcHandler));
  route_42_maritime_v1_rpc.patch(adaptVercelHandler(route_42_maritime_v1_rpcHandler));
  route_42_maritime_v1_rpc.delete(adaptVercelHandler(route_42_maritime_v1_rpcHandler));
  route_42_maritime_v1_rpc.options(adaptVercelHandler(route_42_maritime_v1_rpcHandler));
  const route_43_market_v1_rpc = api.route('/api/market/v1/:rpc');
  route_43_market_v1_rpc.get(adaptVercelHandler(route_43_market_v1_rpcHandler));
  route_43_market_v1_rpc.post(adaptVercelHandler(route_43_market_v1_rpcHandler));
  route_43_market_v1_rpc.put(adaptVercelHandler(route_43_market_v1_rpcHandler));
  route_43_market_v1_rpc.patch(adaptVercelHandler(route_43_market_v1_rpcHandler));
  route_43_market_v1_rpc.delete(adaptVercelHandler(route_43_market_v1_rpcHandler));
  route_43_market_v1_rpc.options(adaptVercelHandler(route_43_market_v1_rpcHandler));
  const route_44_mcp_proxy = api.route('/api/mcp-proxy');
  route_44_mcp_proxy.get(adaptVercelHandler(route_44_mcp_proxyHandler));
  route_44_mcp_proxy.post(adaptVercelHandler(route_44_mcp_proxyHandler));
  route_44_mcp_proxy.put(adaptVercelHandler(route_44_mcp_proxyHandler));
  route_44_mcp_proxy.patch(adaptVercelHandler(route_44_mcp_proxyHandler));
  route_44_mcp_proxy.delete(adaptVercelHandler(route_44_mcp_proxyHandler));
  route_44_mcp_proxy.options(adaptVercelHandler(route_44_mcp_proxyHandler));
  const route_45_me_entitlement = api.route('/api/me/entitlement');
  route_45_me_entitlement.get(adaptVercelHandler(route_45_me_entitlementHandler));
  route_45_me_entitlement.post(adaptVercelHandler(route_45_me_entitlementHandler));
  route_45_me_entitlement.put(adaptVercelHandler(route_45_me_entitlementHandler));
  route_45_me_entitlement.patch(adaptVercelHandler(route_45_me_entitlementHandler));
  route_45_me_entitlement.delete(adaptVercelHandler(route_45_me_entitlementHandler));
  route_45_me_entitlement.options(adaptVercelHandler(route_45_me_entitlementHandler));
  const route_46_military_v1_rpc = api.route('/api/military/v1/:rpc');
  route_46_military_v1_rpc.get(adaptVercelHandler(route_46_military_v1_rpcHandler));
  route_46_military_v1_rpc.post(adaptVercelHandler(route_46_military_v1_rpcHandler));
  route_46_military_v1_rpc.put(adaptVercelHandler(route_46_military_v1_rpcHandler));
  route_46_military_v1_rpc.patch(adaptVercelHandler(route_46_military_v1_rpcHandler));
  route_46_military_v1_rpc.delete(adaptVercelHandler(route_46_military_v1_rpcHandler));
  route_46_military_v1_rpc.options(adaptVercelHandler(route_46_military_v1_rpcHandler));
  const route_47_natural_v1_rpc = api.route('/api/natural/v1/:rpc');
  route_47_natural_v1_rpc.get(adaptVercelHandler(route_47_natural_v1_rpcHandler));
  route_47_natural_v1_rpc.post(adaptVercelHandler(route_47_natural_v1_rpcHandler));
  route_47_natural_v1_rpc.put(adaptVercelHandler(route_47_natural_v1_rpcHandler));
  route_47_natural_v1_rpc.patch(adaptVercelHandler(route_47_natural_v1_rpcHandler));
  route_47_natural_v1_rpc.delete(adaptVercelHandler(route_47_natural_v1_rpcHandler));
  route_47_natural_v1_rpc.options(adaptVercelHandler(route_47_natural_v1_rpcHandler));
  const route_48_news_v1_rpc = api.route('/api/news/v1/:rpc');
  route_48_news_v1_rpc.get(adaptVercelHandler(route_48_news_v1_rpcHandler));
  route_48_news_v1_rpc.post(adaptVercelHandler(route_48_news_v1_rpcHandler));
  route_48_news_v1_rpc.put(adaptVercelHandler(route_48_news_v1_rpcHandler));
  route_48_news_v1_rpc.patch(adaptVercelHandler(route_48_news_v1_rpcHandler));
  route_48_news_v1_rpc.delete(adaptVercelHandler(route_48_news_v1_rpcHandler));
  route_48_news_v1_rpc.options(adaptVercelHandler(route_48_news_v1_rpcHandler));
  const route_49_not_found = api.route('/api/not-found');
  route_49_not_found.get(adaptVercelHandler(route_49_not_foundHandler));
  route_49_not_found.post(adaptVercelHandler(route_49_not_foundHandler));
  route_49_not_found.put(adaptVercelHandler(route_49_not_foundHandler));
  route_49_not_found.patch(adaptVercelHandler(route_49_not_foundHandler));
  route_49_not_found.delete(adaptVercelHandler(route_49_not_foundHandler));
  route_49_not_found.options(adaptVercelHandler(route_49_not_foundHandler));
  const route_50_notification_channels = api.route('/api/notification-channels');
  route_50_notification_channels.get(adaptVercelHandler(route_50_notification_channelsHandler));
  route_50_notification_channels.post(adaptVercelHandler(route_50_notification_channelsHandler));
  route_50_notification_channels.put(adaptVercelHandler(route_50_notification_channelsHandler));
  route_50_notification_channels.patch(adaptVercelHandler(route_50_notification_channelsHandler));
  route_50_notification_channels.delete(adaptVercelHandler(route_50_notification_channelsHandler));
  route_50_notification_channels.options(adaptVercelHandler(route_50_notification_channelsHandler));
  const route_51_notify = api.route('/api/notify');
  route_51_notify.get(adaptVercelHandler(route_51_notifyHandler));
  route_51_notify.post(adaptVercelHandler(route_51_notifyHandler));
  route_51_notify.put(adaptVercelHandler(route_51_notifyHandler));
  route_51_notify.patch(adaptVercelHandler(route_51_notifyHandler));
  route_51_notify.delete(adaptVercelHandler(route_51_notifyHandler));
  route_51_notify.options(adaptVercelHandler(route_51_notifyHandler));
  const route_52_oauth_authorization_server = api.route('/api/oauth-authorization-server');
  route_52_oauth_authorization_server.get(adaptVercelHandler(route_52_oauth_authorization_serverHandler));
  route_52_oauth_authorization_server.post(adaptVercelHandler(route_52_oauth_authorization_serverHandler));
  route_52_oauth_authorization_server.put(adaptVercelHandler(route_52_oauth_authorization_serverHandler));
  route_52_oauth_authorization_server.patch(adaptVercelHandler(route_52_oauth_authorization_serverHandler));
  route_52_oauth_authorization_server.delete(adaptVercelHandler(route_52_oauth_authorization_serverHandler));
  route_52_oauth_authorization_server.options(adaptVercelHandler(route_52_oauth_authorization_serverHandler));
  const route_53_oauth_protected_resource = api.route('/api/oauth-protected-resource');
  route_53_oauth_protected_resource.get(adaptVercelHandler(route_53_oauth_protected_resourceHandler));
  route_53_oauth_protected_resource.post(adaptVercelHandler(route_53_oauth_protected_resourceHandler));
  route_53_oauth_protected_resource.put(adaptVercelHandler(route_53_oauth_protected_resourceHandler));
  route_53_oauth_protected_resource.patch(adaptVercelHandler(route_53_oauth_protected_resourceHandler));
  route_53_oauth_protected_resource.delete(adaptVercelHandler(route_53_oauth_protected_resourceHandler));
  route_53_oauth_protected_resource.options(adaptVercelHandler(route_53_oauth_protected_resourceHandler));
  const route_54_oauth_authorize_pro = api.route('/api/oauth/authorize-pro');
  route_54_oauth_authorize_pro.get(adaptVercelHandler(route_54_oauth_authorize_proHandler));
  route_54_oauth_authorize_pro.post(adaptVercelHandler(route_54_oauth_authorize_proHandler));
  route_54_oauth_authorize_pro.put(adaptVercelHandler(route_54_oauth_authorize_proHandler));
  route_54_oauth_authorize_pro.patch(adaptVercelHandler(route_54_oauth_authorize_proHandler));
  route_54_oauth_authorize_pro.delete(adaptVercelHandler(route_54_oauth_authorize_proHandler));
  route_54_oauth_authorize_pro.options(adaptVercelHandler(route_54_oauth_authorize_proHandler));
  const route_55_oauth_authorize = api.route('/api/oauth/authorize');
  route_55_oauth_authorize.get(adaptVercelHandler(route_55_oauth_authorizeHandler));
  route_55_oauth_authorize.post(adaptVercelHandler(route_55_oauth_authorizeHandler));
  route_55_oauth_authorize.put(adaptVercelHandler(route_55_oauth_authorizeHandler));
  route_55_oauth_authorize.patch(adaptVercelHandler(route_55_oauth_authorizeHandler));
  route_55_oauth_authorize.delete(adaptVercelHandler(route_55_oauth_authorizeHandler));
  route_55_oauth_authorize.options(adaptVercelHandler(route_55_oauth_authorizeHandler));
  const route_56_oauth_register = api.route('/api/oauth/register');
  route_56_oauth_register.get(adaptVercelHandler(route_56_oauth_registerHandler));
  route_56_oauth_register.post(adaptVercelHandler(route_56_oauth_registerHandler));
  route_56_oauth_register.put(adaptVercelHandler(route_56_oauth_registerHandler));
  route_56_oauth_register.patch(adaptVercelHandler(route_56_oauth_registerHandler));
  route_56_oauth_register.delete(adaptVercelHandler(route_56_oauth_registerHandler));
  route_56_oauth_register.options(adaptVercelHandler(route_56_oauth_registerHandler));
  const route_57_oauth_token = api.route('/api/oauth/token');
  route_57_oauth_token.get(adaptVercelHandler(route_57_oauth_tokenHandler));
  route_57_oauth_token.post(adaptVercelHandler(route_57_oauth_tokenHandler));
  route_57_oauth_token.put(adaptVercelHandler(route_57_oauth_tokenHandler));
  route_57_oauth_token.patch(adaptVercelHandler(route_57_oauth_tokenHandler));
  route_57_oauth_token.delete(adaptVercelHandler(route_57_oauth_tokenHandler));
  route_57_oauth_token.options(adaptVercelHandler(route_57_oauth_tokenHandler));
  const route_58_opensky = api.route('/api/opensky');
  route_58_opensky.get(adaptVercelHandler(route_58_openskyHandler));
  route_58_opensky.post(adaptVercelHandler(route_58_openskyHandler));
  route_58_opensky.put(adaptVercelHandler(route_58_openskyHandler));
  route_58_opensky.patch(adaptVercelHandler(route_58_openskyHandler));
  route_58_opensky.delete(adaptVercelHandler(route_58_openskyHandler));
  route_58_opensky.options(adaptVercelHandler(route_58_openskyHandler));
  const route_59_oref_alerts = api.route('/api/oref-alerts');
  route_59_oref_alerts.get(adaptVercelHandler(route_59_oref_alertsHandler));
  route_59_oref_alerts.post(adaptVercelHandler(route_59_oref_alertsHandler));
  route_59_oref_alerts.put(adaptVercelHandler(route_59_oref_alertsHandler));
  route_59_oref_alerts.patch(adaptVercelHandler(route_59_oref_alertsHandler));
  route_59_oref_alerts.delete(adaptVercelHandler(route_59_oref_alertsHandler));
  route_59_oref_alerts.options(adaptVercelHandler(route_59_oref_alertsHandler));
  const route_60_polymarket = api.route('/api/polymarket');
  route_60_polymarket.get(adaptVercelHandler(route_60_polymarketHandler));
  route_60_polymarket.post(adaptVercelHandler(route_60_polymarketHandler));
  route_60_polymarket.put(adaptVercelHandler(route_60_polymarketHandler));
  route_60_polymarket.patch(adaptVercelHandler(route_60_polymarketHandler));
  route_60_polymarket.delete(adaptVercelHandler(route_60_polymarketHandler));
  route_60_polymarket.options(adaptVercelHandler(route_60_polymarketHandler));
  const route_61_positive_events_v1_rpc = api.route('/api/positive-events/v1/:rpc');
  route_61_positive_events_v1_rpc.get(adaptVercelHandler(route_61_positive_events_v1_rpcHandler));
  route_61_positive_events_v1_rpc.post(adaptVercelHandler(route_61_positive_events_v1_rpcHandler));
  route_61_positive_events_v1_rpc.put(adaptVercelHandler(route_61_positive_events_v1_rpcHandler));
  route_61_positive_events_v1_rpc.patch(adaptVercelHandler(route_61_positive_events_v1_rpcHandler));
  route_61_positive_events_v1_rpc.delete(adaptVercelHandler(route_61_positive_events_v1_rpcHandler));
  route_61_positive_events_v1_rpc.options(adaptVercelHandler(route_61_positive_events_v1_rpcHandler));
  const route_62_prediction_v1_rpc = api.route('/api/prediction/v1/:rpc');
  route_62_prediction_v1_rpc.get(adaptVercelHandler(route_62_prediction_v1_rpcHandler));
  route_62_prediction_v1_rpc.post(adaptVercelHandler(route_62_prediction_v1_rpcHandler));
  route_62_prediction_v1_rpc.put(adaptVercelHandler(route_62_prediction_v1_rpcHandler));
  route_62_prediction_v1_rpc.patch(adaptVercelHandler(route_62_prediction_v1_rpcHandler));
  route_62_prediction_v1_rpc.delete(adaptVercelHandler(route_62_prediction_v1_rpcHandler));
  route_62_prediction_v1_rpc.options(adaptVercelHandler(route_62_prediction_v1_rpcHandler));
  const route_63_product_catalog = api.route('/api/product-catalog');
  route_63_product_catalog.get(adaptVercelHandler(route_63_product_catalogHandler));
  route_63_product_catalog.post(adaptVercelHandler(route_63_product_catalogHandler));
  route_63_product_catalog.put(adaptVercelHandler(route_63_product_catalogHandler));
  route_63_product_catalog.patch(adaptVercelHandler(route_63_product_catalogHandler));
  route_63_product_catalog.delete(adaptVercelHandler(route_63_product_catalogHandler));
  route_63_product_catalog.options(adaptVercelHandler(route_63_product_catalogHandler));
  const route_64_radiation_v1_rpc = api.route('/api/radiation/v1/:rpc');
  route_64_radiation_v1_rpc.get(adaptVercelHandler(route_64_radiation_v1_rpcHandler));
  route_64_radiation_v1_rpc.post(adaptVercelHandler(route_64_radiation_v1_rpcHandler));
  route_64_radiation_v1_rpc.put(adaptVercelHandler(route_64_radiation_v1_rpcHandler));
  route_64_radiation_v1_rpc.patch(adaptVercelHandler(route_64_radiation_v1_rpcHandler));
  route_64_radiation_v1_rpc.delete(adaptVercelHandler(route_64_radiation_v1_rpcHandler));
  route_64_radiation_v1_rpc.options(adaptVercelHandler(route_64_radiation_v1_rpcHandler));
  const route_65_referral_me = api.route('/api/referral/me');
  route_65_referral_me.get(adaptVercelHandler(route_65_referral_meHandler));
  route_65_referral_me.post(adaptVercelHandler(route_65_referral_meHandler));
  route_65_referral_me.put(adaptVercelHandler(route_65_referral_meHandler));
  route_65_referral_me.patch(adaptVercelHandler(route_65_referral_meHandler));
  route_65_referral_me.delete(adaptVercelHandler(route_65_referral_meHandler));
  route_65_referral_me.options(adaptVercelHandler(route_65_referral_meHandler));
  const route_66_research_v1_rpc = api.route('/api/research/v1/:rpc');
  route_66_research_v1_rpc.get(adaptVercelHandler(route_66_research_v1_rpcHandler));
  route_66_research_v1_rpc.post(adaptVercelHandler(route_66_research_v1_rpcHandler));
  route_66_research_v1_rpc.put(adaptVercelHandler(route_66_research_v1_rpcHandler));
  route_66_research_v1_rpc.patch(adaptVercelHandler(route_66_research_v1_rpcHandler));
  route_66_research_v1_rpc.delete(adaptVercelHandler(route_66_research_v1_rpcHandler));
  route_66_research_v1_rpc.options(adaptVercelHandler(route_66_research_v1_rpcHandler));
  const route_67_resilience_v1_rpc = api.route('/api/resilience/v1/:rpc');
  route_67_resilience_v1_rpc.get(adaptVercelHandler(route_67_resilience_v1_rpcHandler));
  route_67_resilience_v1_rpc.post(adaptVercelHandler(route_67_resilience_v1_rpcHandler));
  route_67_resilience_v1_rpc.put(adaptVercelHandler(route_67_resilience_v1_rpcHandler));
  route_67_resilience_v1_rpc.patch(adaptVercelHandler(route_67_resilience_v1_rpcHandler));
  route_67_resilience_v1_rpc.delete(adaptVercelHandler(route_67_resilience_v1_rpcHandler));
  route_67_resilience_v1_rpc.options(adaptVercelHandler(route_67_resilience_v1_rpcHandler));
  const route_68_reverse_geocode = api.route('/api/reverse-geocode');
  route_68_reverse_geocode.get(adaptVercelHandler(route_68_reverse_geocodeHandler));
  route_68_reverse_geocode.post(adaptVercelHandler(route_68_reverse_geocodeHandler));
  route_68_reverse_geocode.put(adaptVercelHandler(route_68_reverse_geocodeHandler));
  route_68_reverse_geocode.patch(adaptVercelHandler(route_68_reverse_geocodeHandler));
  route_68_reverse_geocode.delete(adaptVercelHandler(route_68_reverse_geocodeHandler));
  route_68_reverse_geocode.options(adaptVercelHandler(route_68_reverse_geocodeHandler));
  const route_69_rss_proxy = api.route('/api/rss-proxy');
  route_69_rss_proxy.get(adaptVercelHandler(route_69_rss_proxyHandler));
  route_69_rss_proxy.post(adaptVercelHandler(route_69_rss_proxyHandler));
  route_69_rss_proxy.put(adaptVercelHandler(route_69_rss_proxyHandler));
  route_69_rss_proxy.patch(adaptVercelHandler(route_69_rss_proxyHandler));
  route_69_rss_proxy.delete(adaptVercelHandler(route_69_rss_proxyHandler));
  route_69_rss_proxy.options(adaptVercelHandler(route_69_rss_proxyHandler));
  const route_70_sanctions_v1_rpc = api.route('/api/sanctions/v1/:rpc');
  route_70_sanctions_v1_rpc.get(adaptVercelHandler(route_70_sanctions_v1_rpcHandler));
  route_70_sanctions_v1_rpc.post(adaptVercelHandler(route_70_sanctions_v1_rpcHandler));
  route_70_sanctions_v1_rpc.put(adaptVercelHandler(route_70_sanctions_v1_rpcHandler));
  route_70_sanctions_v1_rpc.patch(adaptVercelHandler(route_70_sanctions_v1_rpcHandler));
  route_70_sanctions_v1_rpc.delete(adaptVercelHandler(route_70_sanctions_v1_rpcHandler));
  route_70_sanctions_v1_rpc.options(adaptVercelHandler(route_70_sanctions_v1_rpcHandler));
  const route_71_scenario_v1_rpc = api.route('/api/scenario/v1/:rpc');
  route_71_scenario_v1_rpc.get(adaptVercelHandler(route_71_scenario_v1_rpcHandler));
  route_71_scenario_v1_rpc.post(adaptVercelHandler(route_71_scenario_v1_rpcHandler));
  route_71_scenario_v1_rpc.put(adaptVercelHandler(route_71_scenario_v1_rpcHandler));
  route_71_scenario_v1_rpc.patch(adaptVercelHandler(route_71_scenario_v1_rpcHandler));
  route_71_scenario_v1_rpc.delete(adaptVercelHandler(route_71_scenario_v1_rpcHandler));
  route_71_scenario_v1_rpc.options(adaptVercelHandler(route_71_scenario_v1_rpcHandler));
  const route_72_scenario_v1_run = api.route('/api/scenario/v1/run');
  route_72_scenario_v1_run.get(adaptVercelHandler(route_72_scenario_v1_runHandler));
  route_72_scenario_v1_run.post(adaptVercelHandler(route_72_scenario_v1_runHandler));
  route_72_scenario_v1_run.put(adaptVercelHandler(route_72_scenario_v1_runHandler));
  route_72_scenario_v1_run.patch(adaptVercelHandler(route_72_scenario_v1_runHandler));
  route_72_scenario_v1_run.delete(adaptVercelHandler(route_72_scenario_v1_runHandler));
  route_72_scenario_v1_run.options(adaptVercelHandler(route_72_scenario_v1_runHandler));
  const route_73_scenario_v1_status = api.route('/api/scenario/v1/status');
  route_73_scenario_v1_status.get(adaptVercelHandler(route_73_scenario_v1_statusHandler));
  route_73_scenario_v1_status.post(adaptVercelHandler(route_73_scenario_v1_statusHandler));
  route_73_scenario_v1_status.put(adaptVercelHandler(route_73_scenario_v1_statusHandler));
  route_73_scenario_v1_status.patch(adaptVercelHandler(route_73_scenario_v1_statusHandler));
  route_73_scenario_v1_status.delete(adaptVercelHandler(route_73_scenario_v1_statusHandler));
  route_73_scenario_v1_status.options(adaptVercelHandler(route_73_scenario_v1_statusHandler));
  const route_74_scenario_v1_templates = api.route('/api/scenario/v1/templates');
  route_74_scenario_v1_templates.get(adaptVercelHandler(route_74_scenario_v1_templatesHandler));
  route_74_scenario_v1_templates.post(adaptVercelHandler(route_74_scenario_v1_templatesHandler));
  route_74_scenario_v1_templates.put(adaptVercelHandler(route_74_scenario_v1_templatesHandler));
  route_74_scenario_v1_templates.patch(adaptVercelHandler(route_74_scenario_v1_templatesHandler));
  route_74_scenario_v1_templates.delete(adaptVercelHandler(route_74_scenario_v1_templatesHandler));
  route_74_scenario_v1_templates.options(adaptVercelHandler(route_74_scenario_v1_templatesHandler));
  const route_75_security_report = api.route('/api/security/report');
  route_75_security_report.get(adaptVercelHandler(route_75_security_reportHandler));
  route_75_security_report.post(adaptVercelHandler(route_75_security_reportHandler));
  route_75_security_report.put(adaptVercelHandler(route_75_security_reportHandler));
  route_75_security_report.patch(adaptVercelHandler(route_75_security_reportHandler));
  route_75_security_report.delete(adaptVercelHandler(route_75_security_reportHandler));
  route_75_security_report.options(adaptVercelHandler(route_75_security_reportHandler));
  const route_76_seed_contract_probe = api.route('/api/seed-contract-probe');
  route_76_seed_contract_probe.get(adaptVercelHandler(route_76_seed_contract_probeHandler));
  route_76_seed_contract_probe.post(adaptVercelHandler(route_76_seed_contract_probeHandler));
  route_76_seed_contract_probe.put(adaptVercelHandler(route_76_seed_contract_probeHandler));
  route_76_seed_contract_probe.patch(adaptVercelHandler(route_76_seed_contract_probeHandler));
  route_76_seed_contract_probe.delete(adaptVercelHandler(route_76_seed_contract_probeHandler));
  route_76_seed_contract_probe.options(adaptVercelHandler(route_76_seed_contract_probeHandler));
  const route_77_seed_health = api.route('/api/seed-health');
  route_77_seed_health.get(adaptVercelHandler(route_77_seed_healthHandler));
  route_77_seed_health.post(adaptVercelHandler(route_77_seed_healthHandler));
  route_77_seed_health.put(adaptVercelHandler(route_77_seed_healthHandler));
  route_77_seed_health.patch(adaptVercelHandler(route_77_seed_healthHandler));
  route_77_seed_health.delete(adaptVercelHandler(route_77_seed_healthHandler));
  route_77_seed_health.options(adaptVercelHandler(route_77_seed_healthHandler));
  const route_78_seismology_v1_rpc = api.route('/api/seismology/v1/:rpc');
  route_78_seismology_v1_rpc.get(adaptVercelHandler(route_78_seismology_v1_rpcHandler));
  route_78_seismology_v1_rpc.post(adaptVercelHandler(route_78_seismology_v1_rpcHandler));
  route_78_seismology_v1_rpc.put(adaptVercelHandler(route_78_seismology_v1_rpcHandler));
  route_78_seismology_v1_rpc.patch(adaptVercelHandler(route_78_seismology_v1_rpcHandler));
  route_78_seismology_v1_rpc.delete(adaptVercelHandler(route_78_seismology_v1_rpcHandler));
  route_78_seismology_v1_rpc.options(adaptVercelHandler(route_78_seismology_v1_rpcHandler));
  const route_79_skills_fetch_agentskills = api.route('/api/skills/fetch-agentskills');
  route_79_skills_fetch_agentskills.get(adaptVercelHandler(route_79_skills_fetch_agentskillsHandler));
  route_79_skills_fetch_agentskills.post(adaptVercelHandler(route_79_skills_fetch_agentskillsHandler));
  route_79_skills_fetch_agentskills.put(adaptVercelHandler(route_79_skills_fetch_agentskillsHandler));
  route_79_skills_fetch_agentskills.patch(adaptVercelHandler(route_79_skills_fetch_agentskillsHandler));
  route_79_skills_fetch_agentskills.delete(adaptVercelHandler(route_79_skills_fetch_agentskillsHandler));
  route_79_skills_fetch_agentskills.options(adaptVercelHandler(route_79_skills_fetch_agentskillsHandler));
  const route_80_slack_oauth_callback = api.route('/api/slack/oauth/callback');
  route_80_slack_oauth_callback.get(adaptVercelHandler(route_80_slack_oauth_callbackHandler));
  route_80_slack_oauth_callback.post(adaptVercelHandler(route_80_slack_oauth_callbackHandler));
  route_80_slack_oauth_callback.put(adaptVercelHandler(route_80_slack_oauth_callbackHandler));
  route_80_slack_oauth_callback.patch(adaptVercelHandler(route_80_slack_oauth_callbackHandler));
  route_80_slack_oauth_callback.delete(adaptVercelHandler(route_80_slack_oauth_callbackHandler));
  route_80_slack_oauth_callback.options(adaptVercelHandler(route_80_slack_oauth_callbackHandler));
  const route_81_slack_oauth_start = api.route('/api/slack/oauth/start');
  route_81_slack_oauth_start.get(adaptVercelHandler(route_81_slack_oauth_startHandler));
  route_81_slack_oauth_start.post(adaptVercelHandler(route_81_slack_oauth_startHandler));
  route_81_slack_oauth_start.put(adaptVercelHandler(route_81_slack_oauth_startHandler));
  route_81_slack_oauth_start.patch(adaptVercelHandler(route_81_slack_oauth_startHandler));
  route_81_slack_oauth_start.delete(adaptVercelHandler(route_81_slack_oauth_startHandler));
  route_81_slack_oauth_start.options(adaptVercelHandler(route_81_slack_oauth_startHandler));
  const route_82_supply_chain_hormuz_tracker = api.route('/api/supply-chain/hormuz-tracker');
  route_82_supply_chain_hormuz_tracker.get(adaptVercelHandler(route_82_supply_chain_hormuz_trackerHandler));
  route_82_supply_chain_hormuz_tracker.post(adaptVercelHandler(route_82_supply_chain_hormuz_trackerHandler));
  route_82_supply_chain_hormuz_tracker.put(adaptVercelHandler(route_82_supply_chain_hormuz_trackerHandler));
  route_82_supply_chain_hormuz_tracker.patch(adaptVercelHandler(route_82_supply_chain_hormuz_trackerHandler));
  route_82_supply_chain_hormuz_tracker.delete(adaptVercelHandler(route_82_supply_chain_hormuz_trackerHandler));
  route_82_supply_chain_hormuz_tracker.options(adaptVercelHandler(route_82_supply_chain_hormuz_trackerHandler));
  const route_83_supply_chain_v1_rpc = api.route('/api/supply-chain/v1/:rpc');
  route_83_supply_chain_v1_rpc.get(adaptVercelHandler(route_83_supply_chain_v1_rpcHandler));
  route_83_supply_chain_v1_rpc.post(adaptVercelHandler(route_83_supply_chain_v1_rpcHandler));
  route_83_supply_chain_v1_rpc.put(adaptVercelHandler(route_83_supply_chain_v1_rpcHandler));
  route_83_supply_chain_v1_rpc.patch(adaptVercelHandler(route_83_supply_chain_v1_rpcHandler));
  route_83_supply_chain_v1_rpc.delete(adaptVercelHandler(route_83_supply_chain_v1_rpcHandler));
  route_83_supply_chain_v1_rpc.options(adaptVercelHandler(route_83_supply_chain_v1_rpcHandler));
  const route_84_supply_chain_v1_country_products = api.route('/api/supply-chain/v1/country-products');
  route_84_supply_chain_v1_country_products.get(adaptVercelHandler(route_84_supply_chain_v1_country_productsHandler));
  route_84_supply_chain_v1_country_products.post(adaptVercelHandler(route_84_supply_chain_v1_country_productsHandler));
  route_84_supply_chain_v1_country_products.put(adaptVercelHandler(route_84_supply_chain_v1_country_productsHandler));
  route_84_supply_chain_v1_country_products.patch(adaptVercelHandler(route_84_supply_chain_v1_country_productsHandler));
  route_84_supply_chain_v1_country_products.delete(adaptVercelHandler(route_84_supply_chain_v1_country_productsHandler));
  route_84_supply_chain_v1_country_products.options(adaptVercelHandler(route_84_supply_chain_v1_country_productsHandler));
  const route_85_supply_chain_v1_multi_sector_cost_shock = api.route('/api/supply-chain/v1/multi-sector-cost-shock');
  route_85_supply_chain_v1_multi_sector_cost_shock.get(adaptVercelHandler(route_85_supply_chain_v1_multi_sector_cost_shockHandler));
  route_85_supply_chain_v1_multi_sector_cost_shock.post(adaptVercelHandler(route_85_supply_chain_v1_multi_sector_cost_shockHandler));
  route_85_supply_chain_v1_multi_sector_cost_shock.put(adaptVercelHandler(route_85_supply_chain_v1_multi_sector_cost_shockHandler));
  route_85_supply_chain_v1_multi_sector_cost_shock.patch(adaptVercelHandler(route_85_supply_chain_v1_multi_sector_cost_shockHandler));
  route_85_supply_chain_v1_multi_sector_cost_shock.delete(adaptVercelHandler(route_85_supply_chain_v1_multi_sector_cost_shockHandler));
  route_85_supply_chain_v1_multi_sector_cost_shock.options(adaptVercelHandler(route_85_supply_chain_v1_multi_sector_cost_shockHandler));
  const route_86_symbol_search = api.route('/api/symbol-search');
  route_86_symbol_search.get(adaptVercelHandler(route_86_symbol_searchHandler));
  route_86_symbol_search.post(adaptVercelHandler(route_86_symbol_searchHandler));
  route_86_symbol_search.put(adaptVercelHandler(route_86_symbol_searchHandler));
  route_86_symbol_search.patch(adaptVercelHandler(route_86_symbol_searchHandler));
  route_86_symbol_search.delete(adaptVercelHandler(route_86_symbol_searchHandler));
  route_86_symbol_search.options(adaptVercelHandler(route_86_symbol_searchHandler));
  const route_87_telegram_feed = api.route('/api/telegram-feed');
  route_87_telegram_feed.get(adaptVercelHandler(route_87_telegram_feedHandler));
  route_87_telegram_feed.post(adaptVercelHandler(route_87_telegram_feedHandler));
  route_87_telegram_feed.put(adaptVercelHandler(route_87_telegram_feedHandler));
  route_87_telegram_feed.patch(adaptVercelHandler(route_87_telegram_feedHandler));
  route_87_telegram_feed.delete(adaptVercelHandler(route_87_telegram_feedHandler));
  route_87_telegram_feed.options(adaptVercelHandler(route_87_telegram_feedHandler));
  const route_88_telegram_pair_callback = api.route('/api/telegram/pair-callback');
  route_88_telegram_pair_callback.get(adaptVercelHandler(route_88_telegram_pair_callbackHandler));
  route_88_telegram_pair_callback.post(adaptVercelHandler(route_88_telegram_pair_callbackHandler));
  route_88_telegram_pair_callback.put(adaptVercelHandler(route_88_telegram_pair_callbackHandler));
  route_88_telegram_pair_callback.patch(adaptVercelHandler(route_88_telegram_pair_callbackHandler));
  route_88_telegram_pair_callback.delete(adaptVercelHandler(route_88_telegram_pair_callbackHandler));
  route_88_telegram_pair_callback.options(adaptVercelHandler(route_88_telegram_pair_callbackHandler));
  const route_89_thermal_v1_rpc = api.route('/api/thermal/v1/:rpc');
  route_89_thermal_v1_rpc.get(adaptVercelHandler(route_89_thermal_v1_rpcHandler));
  route_89_thermal_v1_rpc.post(adaptVercelHandler(route_89_thermal_v1_rpcHandler));
  route_89_thermal_v1_rpc.put(adaptVercelHandler(route_89_thermal_v1_rpcHandler));
  route_89_thermal_v1_rpc.patch(adaptVercelHandler(route_89_thermal_v1_rpcHandler));
  route_89_thermal_v1_rpc.delete(adaptVercelHandler(route_89_thermal_v1_rpcHandler));
  route_89_thermal_v1_rpc.options(adaptVercelHandler(route_89_thermal_v1_rpcHandler));
  const route_90_trade_v1_rpc = api.route('/api/trade/v1/:rpc');
  route_90_trade_v1_rpc.get(adaptVercelHandler(route_90_trade_v1_rpcHandler));
  route_90_trade_v1_rpc.post(adaptVercelHandler(route_90_trade_v1_rpcHandler));
  route_90_trade_v1_rpc.put(adaptVercelHandler(route_90_trade_v1_rpcHandler));
  route_90_trade_v1_rpc.patch(adaptVercelHandler(route_90_trade_v1_rpcHandler));
  route_90_trade_v1_rpc.delete(adaptVercelHandler(route_90_trade_v1_rpcHandler));
  route_90_trade_v1_rpc.options(adaptVercelHandler(route_90_trade_v1_rpcHandler));
  const route_91_unrest_v1_rpc = api.route('/api/unrest/v1/:rpc');
  route_91_unrest_v1_rpc.get(adaptVercelHandler(route_91_unrest_v1_rpcHandler));
  route_91_unrest_v1_rpc.post(adaptVercelHandler(route_91_unrest_v1_rpcHandler));
  route_91_unrest_v1_rpc.put(adaptVercelHandler(route_91_unrest_v1_rpcHandler));
  route_91_unrest_v1_rpc.patch(adaptVercelHandler(route_91_unrest_v1_rpcHandler));
  route_91_unrest_v1_rpc.delete(adaptVercelHandler(route_91_unrest_v1_rpcHandler));
  route_91_unrest_v1_rpc.options(adaptVercelHandler(route_91_unrest_v1_rpcHandler));
  const route_92_user_prefs = api.route('/api/user-prefs');
  route_92_user_prefs.get(adaptVercelHandler(route_92_user_prefsHandler));
  route_92_user_prefs.post(adaptVercelHandler(route_92_user_prefsHandler));
  route_92_user_prefs.put(adaptVercelHandler(route_92_user_prefsHandler));
  route_92_user_prefs.patch(adaptVercelHandler(route_92_user_prefsHandler));
  route_92_user_prefs.delete(adaptVercelHandler(route_92_user_prefsHandler));
  route_92_user_prefs.options(adaptVercelHandler(route_92_user_prefsHandler));
  const route_93_user_mcp_quota = api.route('/api/user/mcp-quota');
  route_93_user_mcp_quota.get(adaptVercelHandler(route_93_user_mcp_quotaHandler));
  route_93_user_mcp_quota.post(adaptVercelHandler(route_93_user_mcp_quotaHandler));
  route_93_user_mcp_quota.put(adaptVercelHandler(route_93_user_mcp_quotaHandler));
  route_93_user_mcp_quota.patch(adaptVercelHandler(route_93_user_mcp_quotaHandler));
  route_93_user_mcp_quota.delete(adaptVercelHandler(route_93_user_mcp_quotaHandler));
  route_93_user_mcp_quota.options(adaptVercelHandler(route_93_user_mcp_quotaHandler));
  const route_94_user_mcp_revoke = api.route('/api/user/mcp-revoke');
  route_94_user_mcp_revoke.get(adaptVercelHandler(route_94_user_mcp_revokeHandler));
  route_94_user_mcp_revoke.post(adaptVercelHandler(route_94_user_mcp_revokeHandler));
  route_94_user_mcp_revoke.put(adaptVercelHandler(route_94_user_mcp_revokeHandler));
  route_94_user_mcp_revoke.patch(adaptVercelHandler(route_94_user_mcp_revokeHandler));
  route_94_user_mcp_revoke.delete(adaptVercelHandler(route_94_user_mcp_revokeHandler));
  route_94_user_mcp_revoke.options(adaptVercelHandler(route_94_user_mcp_revokeHandler));
  const route_95_v2_shipping_rpc = api.route('/api/v2/shipping/:rpc');
  route_95_v2_shipping_rpc.get(adaptVercelHandler(route_95_v2_shipping_rpcHandler));
  route_95_v2_shipping_rpc.post(adaptVercelHandler(route_95_v2_shipping_rpcHandler));
  route_95_v2_shipping_rpc.put(adaptVercelHandler(route_95_v2_shipping_rpcHandler));
  route_95_v2_shipping_rpc.patch(adaptVercelHandler(route_95_v2_shipping_rpcHandler));
  route_95_v2_shipping_rpc.delete(adaptVercelHandler(route_95_v2_shipping_rpcHandler));
  route_95_v2_shipping_rpc.options(adaptVercelHandler(route_95_v2_shipping_rpcHandler));
  const route_96_v2_shipping_webhooks_subscriberId = api.route('/api/v2/shipping/webhooks/:subscriberId');
  route_96_v2_shipping_webhooks_subscriberId.get(adaptVercelHandler(route_96_v2_shipping_webhooks_subscriberIdHandler));
  route_96_v2_shipping_webhooks_subscriberId.post(adaptVercelHandler(route_96_v2_shipping_webhooks_subscriberIdHandler));
  route_96_v2_shipping_webhooks_subscriberId.put(adaptVercelHandler(route_96_v2_shipping_webhooks_subscriberIdHandler));
  route_96_v2_shipping_webhooks_subscriberId.patch(adaptVercelHandler(route_96_v2_shipping_webhooks_subscriberIdHandler));
  route_96_v2_shipping_webhooks_subscriberId.delete(adaptVercelHandler(route_96_v2_shipping_webhooks_subscriberIdHandler));
  route_96_v2_shipping_webhooks_subscriberId.options(adaptVercelHandler(route_96_v2_shipping_webhooks_subscriberIdHandler));
  const route_97_v2_shipping_webhooks_subscriberId_action = api.route('/api/v2/shipping/webhooks/:subscriberId/:action');
  route_97_v2_shipping_webhooks_subscriberId_action.get(adaptVercelHandler(route_97_v2_shipping_webhooks_subscriberId_actionHandler));
  route_97_v2_shipping_webhooks_subscriberId_action.post(adaptVercelHandler(route_97_v2_shipping_webhooks_subscriberId_actionHandler));
  route_97_v2_shipping_webhooks_subscriberId_action.put(adaptVercelHandler(route_97_v2_shipping_webhooks_subscriberId_actionHandler));
  route_97_v2_shipping_webhooks_subscriberId_action.patch(adaptVercelHandler(route_97_v2_shipping_webhooks_subscriberId_actionHandler));
  route_97_v2_shipping_webhooks_subscriberId_action.delete(adaptVercelHandler(route_97_v2_shipping_webhooks_subscriberId_actionHandler));
  route_97_v2_shipping_webhooks_subscriberId_action.options(adaptVercelHandler(route_97_v2_shipping_webhooks_subscriberId_actionHandler));
  const route_98_version = api.route('/api/version');
  route_98_version.get(adaptVercelHandler(route_98_versionHandler));
  route_98_version.post(adaptVercelHandler(route_98_versionHandler));
  route_98_version.put(adaptVercelHandler(route_98_versionHandler));
  route_98_version.patch(adaptVercelHandler(route_98_versionHandler));
  route_98_version.delete(adaptVercelHandler(route_98_versionHandler));
  route_98_version.options(adaptVercelHandler(route_98_versionHandler));
  const route_99_webcam_v1_rpc = api.route('/api/webcam/v1/:rpc');
  route_99_webcam_v1_rpc.get(adaptVercelHandler(route_99_webcam_v1_rpcHandler));
  route_99_webcam_v1_rpc.post(adaptVercelHandler(route_99_webcam_v1_rpcHandler));
  route_99_webcam_v1_rpc.put(adaptVercelHandler(route_99_webcam_v1_rpcHandler));
  route_99_webcam_v1_rpc.patch(adaptVercelHandler(route_99_webcam_v1_rpcHandler));
  route_99_webcam_v1_rpc.delete(adaptVercelHandler(route_99_webcam_v1_rpcHandler));
  route_99_webcam_v1_rpc.options(adaptVercelHandler(route_99_webcam_v1_rpcHandler));
  const route_100_widget_agent = api.route('/api/widget-agent');
  route_100_widget_agent.get(adaptVercelHandler(route_100_widget_agentHandler));
  route_100_widget_agent.post(adaptVercelHandler(route_100_widget_agentHandler));
  route_100_widget_agent.put(adaptVercelHandler(route_100_widget_agentHandler));
  route_100_widget_agent.patch(adaptVercelHandler(route_100_widget_agentHandler));
  route_100_widget_agent.delete(adaptVercelHandler(route_100_widget_agentHandler));
  route_100_widget_agent.options(adaptVercelHandler(route_100_widget_agentHandler));
  const route_101_wildfire_v1_rpc = api.route('/api/wildfire/v1/:rpc');
  route_101_wildfire_v1_rpc.get(adaptVercelHandler(route_101_wildfire_v1_rpcHandler));
  route_101_wildfire_v1_rpc.post(adaptVercelHandler(route_101_wildfire_v1_rpcHandler));
  route_101_wildfire_v1_rpc.put(adaptVercelHandler(route_101_wildfire_v1_rpcHandler));
  route_101_wildfire_v1_rpc.patch(adaptVercelHandler(route_101_wildfire_v1_rpcHandler));
  route_101_wildfire_v1_rpc.delete(adaptVercelHandler(route_101_wildfire_v1_rpcHandler));
  route_101_wildfire_v1_rpc.options(adaptVercelHandler(route_101_wildfire_v1_rpcHandler));
  const route_102_wm_session = api.route('/api/wm-session');
  route_102_wm_session.get(adaptVercelHandler(route_102_wm_sessionHandler));
  route_102_wm_session.post(adaptVercelHandler(route_102_wm_sessionHandler));
  route_102_wm_session.put(adaptVercelHandler(route_102_wm_sessionHandler));
  route_102_wm_session.patch(adaptVercelHandler(route_102_wm_sessionHandler));
  route_102_wm_session.delete(adaptVercelHandler(route_102_wm_sessionHandler));
  route_102_wm_session.options(adaptVercelHandler(route_102_wm_sessionHandler));
  const route_103_youtube_embed = api.route('/api/youtube/embed');
  route_103_youtube_embed.get(adaptVercelHandler(route_103_youtube_embedHandler));
  route_103_youtube_embed.post(adaptVercelHandler(route_103_youtube_embedHandler));
  route_103_youtube_embed.put(adaptVercelHandler(route_103_youtube_embedHandler));
  route_103_youtube_embed.patch(adaptVercelHandler(route_103_youtube_embedHandler));
  route_103_youtube_embed.delete(adaptVercelHandler(route_103_youtube_embedHandler));
  route_103_youtube_embed.options(adaptVercelHandler(route_103_youtube_embedHandler));
  const route_104_youtube_live = api.route('/api/youtube/live');
  route_104_youtube_live.get(adaptVercelHandler(route_104_youtube_liveHandler));
  route_104_youtube_live.post(adaptVercelHandler(route_104_youtube_liveHandler));
  route_104_youtube_live.put(adaptVercelHandler(route_104_youtube_liveHandler));
  route_104_youtube_live.patch(adaptVercelHandler(route_104_youtube_liveHandler));
  route_104_youtube_live.delete(adaptVercelHandler(route_104_youtube_liveHandler));
  route_104_youtube_live.options(adaptVercelHandler(route_104_youtube_liveHandler));
}
